kind = "mobile"
previewPath = "/ora-mobile/"
title = "MustaFlow"
version = "1.0.0"
id = "artifacts/ora-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/ora-mobile/" ]
localPort = 21457

[services.development]
run = "pnpm --filter @workspace/ora-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ora-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/ora-mobile", "run", "serve" ]

[services.env]
PORT = "21457"
BASE_PATH = "/ora-mobile/"
