export const DATABASE_SQL_MAX_CHARS = 16 * 1024;
export const DATABASE_PARAMETER_MAX_COUNT = 100;
export const DATABASE_BATCH_MAX_STATEMENTS = 20;
export const DATABASE_RESULT_MAX_ROWS = 100;
export const DATABASE_RESULT_MAX_BYTES = 256 * 1024;
export const DATABASE_OPERATION_DEFAULT_TIMEOUT_MS = 10_000;
export const DATABASE_OPERATION_MAX_TIMEOUT_MS = 30_000;
