import { FileText, Shield, AlertTriangle, Scale } from "lucide-react";
import { PageMeta } from "@/components/page-meta";

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12 space-y-10">
      <PageMeta
        title="Terms of Service"
        description="Read the MustaFlow AI Terms of Service. Learn about acceptable use, intellectual property, and your rights as a user."
        path="/terms"
        noIndex={true}
      />
      <div className="space-y-3">
        <div className="flex items-center gap-3">
          <Scale className="h-6 w-6 text-primary" />
          <h1 className="text-2xl font-bold">Terms of Service</h1>
        </div>
        <p className="text-muted-foreground text-sm">
          Last updated: May 2026 — Placeholder document. Final version will be reviewed by legal
          counsel before public launch.
        </p>
      </div>

      <Section icon={FileText} title="1. Acceptance of Terms">
        <p>
          By accessing or using MustaFlow AI ("the Service"), you agree to be bound by these Terms
          of Service. If you do not agree, do not use the Service.
        </p>
      </Section>

      <Section icon={FileText} title="2. Use of the Service">
        <p>
          MustaFlow AI is an AI-powered app builder for generating static web applications. You may
          use the Service only for lawful purposes and in accordance with these terms.
        </p>
        <ul className="list-disc pl-5 space-y-1 mt-2">
          <li>You must not use the Service to generate illegal, harmful, or abusive content.</li>
          <li>
            You must not attempt to reverse engineer, scrape, or abuse the AI generation service.
          </li>
          <li>You are responsible for all content generated using your account.</li>
        </ul>
      </Section>

      <Section icon={Shield} title="3. Account Security">
        <p>
          You are responsible for maintaining the security of your account credentials and any API
          keys or secrets stored in MustaFlow AI. We recommend using separate keys for testing and
          production environments.
        </p>
      </Section>

      <Section icon={AlertTriangle} title="4. AI-Generated Content">
        <p>
          Content generated by AI may contain errors, inaccuracies, or placeholder data. You are
          responsible for reviewing and validating all generated code before deploying it to
          production. MustaFlow AI makes no warranties about the accuracy or fitness for purpose of
          generated content.
        </p>
        <p className="mt-2">
          <strong>Trademark and logo warning:</strong> Do not use third-party logos, trademarks, or
          brand assets in generated apps without authorization from the rights holder.
        </p>
      </Section>

      <Section icon={FileText} title="5. Intellectual Property">
        <p>
          You retain ownership of the apps you build with MustaFlow AI. The underlying platform,
          branding, and codebase of MustaFlow AI remain the property of the operator.
        </p>
      </Section>

      <Section icon={FileText} title="6. Service Availability">
        <p>
          The Service is provided "as is." We reserve the right to modify, suspend, or discontinue
          the Service at any time with reasonable notice.
        </p>
      </Section>

      <Section icon={FileText} title="7. Limitation of Liability">
        <p>
          To the fullest extent permitted by law, MustaFlow AI shall not be liable for any indirect,
          incidental, or consequential damages arising from your use of the Service.
        </p>
      </Section>

      <Section icon={FileText} title="8. Changes to Terms">
        <p>
          We may update these Terms at any time. Continued use of the Service after changes
          constitutes acceptance of the revised Terms.
        </p>
      </Section>

      <div className="border-t border-border pt-6 text-sm text-muted-foreground">
        Questions about these Terms?{" "}
        <a href="/help" className="text-primary hover:underline">
          Contact Support
        </a>
      </div>
    </div>
  );
}

function Section({
  icon: Icon,
  title,
  children,
}: {
  icon: React.ElementType;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <Icon className="h-4 w-4 text-primary shrink-0" />
        <h2 className="font-semibold text-base">{title}</h2>
      </div>
      <div className="text-sm text-muted-foreground leading-relaxed pl-6 space-y-2">{children}</div>
    </div>
  );
}
