import type { OraMessage } from "@/hooks/use-ora-chat";
import type { DatasetAnalysisResult } from "@/types/dataset-analysis";
import { sanitizeForExport, sanitizeTitle, sanitizeSummary, truncateArray } from "./sanitizer";
import { LIMITS } from "./size-limits";
import { triggerDownload, sanitizeFilenameLocal } from "./utils";

export type DocxExportSource =
  | { kind: "dataset"; data: DatasetAnalysisResult; title?: string }
  | { kind: "message"; message: OraMessage; title?: string }
  | { kind: "conversation"; messages: OraMessage[]; title?: string };

function dateStr(): string {
  return new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

export async function downloadDocx(source: DocxExportSource, basename: string): Promise<void> {
  const {
    Document,
    Paragraph,
    TextRun,
    HeadingLevel,
    Table,
    TableRow,
    TableCell,
    WidthType,
    Packer,
  } = await import("docx");

  type Block = InstanceType<typeof Paragraph> | InstanceType<typeof Table>;
  const children: Block[] = [];

  const h1 = (text: string): InstanceType<typeof Paragraph> =>
    new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { before: 400, after: 200 } });

  const h2 = (text: string): InstanceType<typeof Paragraph> =>
    new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 280, after: 120 } });

  const h3 = (text: string): InstanceType<typeof Paragraph> =>
    new Paragraph({ text, heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 80 } });

  const body = (text: string): InstanceType<typeof Paragraph> =>
    new Paragraph({ children: [new TextRun(text)], spacing: { after: 100 } });

  const meta = (text: string): InstanceType<typeof Paragraph> =>
    new Paragraph({ children: [new TextRun({ text, italics: true })], spacing: { after: 80 } });

  const bullet = (text: string): InstanceType<typeof Paragraph> =>
    new Paragraph({
      children: [new TextRun(`\u2022  ${text}`)],
      indent: { left: 360 },
      spacing: { after: 80 },
    });

  const numbered = (text: string, i: number): InstanceType<typeof Paragraph> =>
    new Paragraph({
      children: [new TextRun(`${i + 1}. ${text}`)],
      indent: { left: 360 },
      spacing: { after: 80 },
    });

  const spacer = (): InstanceType<typeof Paragraph> => new Paragraph({ text: "" });

  const headerCell = (text: string): InstanceType<typeof TableCell> =>
    new TableCell({
      children: [
        new Paragraph({ children: [new TextRun({ text, bold: true })], spacing: { after: 60 } }),
      ],
    });

  const dataCell = (text: string): InstanceType<typeof TableCell> =>
    new TableCell({ children: [body(text)] });

  const makeTable = (
    headers: string[],
    rows: string[][],
    widths: number[],
  ): InstanceType<typeof Table> =>
    new Table({
      width: { size: 9000, type: WidthType.DXA },
      columnWidths: widths,
      rows: [
        new TableRow({
          children: headers.map(headerCell),
          tableHeader: true,
        }),
        ...rows.map((row) => new TableRow({ children: row.map(dataCell) })),
      ],
    });

  if (source.kind === "dataset") {
    const data = sanitizeForExport(source.data);
    const title = sanitizeTitle(source.title ?? "Dataset Analysis Report");

    children.push(h1(title));
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: "Analysis Type: ", bold: true }),
          new TextRun(data.analysisType),
        ],
        spacing: { after: 60 },
      }),
    );
    children.push(meta(`Generated: ${dateStr()}  \u00B7  Generated by Ora AI`));
    children.push(spacer());

    children.push(h2("Executive Summary"));
    const summaryLines = sanitizeSummary(data.summary).split("\n");
    summaryLines.forEach((line) => {
      if (line.trim()) children.push(body(line));
      else children.push(spacer());
    });
    children.push(spacer());

    if (data.keyFindings?.length) {
      children.push(h2("Key Findings"));
      truncateArray(data.keyFindings, LIMITS.maxFindings).forEach((f, i) => {
        children.push(numbered(f, i));
      });
      children.push(spacer());
    }

    if (data.kpiGaps?.length) {
      children.push(h2("KPI Performance"));
      const rows = truncateArray(data.kpiGaps, LIMITS.maxKpiRows).map((k) => [
        k.metric,
        k.current,
        k.target ?? "",
        k.gap ?? "",
        k.trend ?? "",
      ]);
      children.push(
        makeTable(
          ["Metric", "Current", "Target", "Gap", "Trend"],
          rows,
          [2800, 1600, 1600, 1500, 1500],
        ),
      );
      children.push(spacer());
    }

    if (data.trendFindings?.length) {
      children.push(h2("Trend Analysis"));
      truncateArray(data.trendFindings, LIMITS.maxTrendRows).forEach((t) => {
        children.push(
          new Paragraph({
            children: [
              t.direction
                ? new TextRun({ text: `[${t.direction.toUpperCase()}]  `, bold: true })
                : new TextRun(""),
              new TextRun(t.description),
            ],
            spacing: { after: 80 },
          }),
        );
      });
      children.push(spacer());
    }

    if (data.paretoFindings?.length) {
      children.push(h2("Pareto Analysis"));
      const rows = truncateArray(data.paretoFindings, LIMITS.maxParetoRows).map((p) => [
        p.label,
        String(p.value),
        p.cumPct != null ? `${p.cumPct.toFixed(1)}%` : "",
      ]);
      children.push(makeTable(["Category", "Value", "Cumulative %"], rows, [4000, 2500, 2500]));
      children.push(spacer());
    }

    if (data.rootCauseAnalysis) {
      const rca = data.rootCauseAnalysis;
      children.push(h2("Root Cause Analysis"));

      if (rca.likelyCauses?.length) {
        children.push(h3("Likely Causes"));
        rca.likelyCauses.forEach((c) => children.push(bullet(c)));
        children.push(spacer());
      }

      if (rca.fiveWhys?.length) {
        children.push(h3("Five Whys"));
        rca.fiveWhys.forEach((why, i) => children.push(numbered(why, i)));
        children.push(spacer());
      }

      if (rca.fishbone) {
        children.push(h3("Fishbone Diagram (Cause Categories)"));
        for (const [category, causes] of Object.entries(rca.fishbone)) {
          children.push(
            new Paragraph({
              children: [new TextRun({ text: category, bold: true })],
              spacing: { after: 60 },
            }),
          );
          causes.forEach((c) => children.push(bullet(c)));
        }
        children.push(spacer());
      }
    }

    if (data.risksAndLimitations?.length) {
      children.push(h2("Risks & Limitations"));
      data.risksAndLimitations.forEach((r) => children.push(bullet(r)));
      children.push(spacer());
    }

    if (data.recommendations?.length) {
      children.push(h2("Recommendations"));
      truncateArray(data.recommendations, LIMITS.maxRecommendations).forEach((r, i) => {
        children.push(numbered(r, i));
      });
      children.push(spacer());
    }

    if (data.actionPlan?.length) {
      children.push(h2("Action Plan"));
      const rows = truncateArray(data.actionPlan, LIMITS.maxActionPlanRows).map((a) => [
        a.action,
        a.priority,
        a.owner ?? "",
        a.timeline ?? "",
      ]);
      children.push(
        makeTable(["Action", "Priority", "Owner", "Timeline"], rows, [3800, 1500, 2000, 1700]),
      );
      children.push(spacer());
    }

    if (data.nextSteps?.length) {
      children.push(h2("Next Steps"));
      data.nextSteps.forEach((s) => children.push(bullet(s)));
    }
  } else if (source.kind === "message") {
    const msg = sanitizeForExport(source.message);
    const title = sanitizeTitle(source.title ?? "Ora Response");
    const roleLabel = msg.role === "user" ? "User" : "Ora";

    children.push(h1(title));
    children.push(meta(`Generated: ${dateStr()}  \u00B7  Generated by Ora AI`));
    children.push(spacer());
    children.push(h2(roleLabel));

    msg.content.split("\n").forEach((line) => {
      if (line.trim()) children.push(body(line));
      else children.push(spacer());
    });
  } else {
    const messages = truncateArray(
      source.messages.map((m) => sanitizeForExport(m)),
      LIMITS.maxDocxSections,
    );
    const title = sanitizeTitle(source.title ?? "Ora Conversation");

    children.push(h1(title));
    children.push(
      meta(
        `Generated: ${dateStr()}  \u00B7  ${messages.length} messages  \u00B7  Generated by Ora AI`,
      ),
    );
    children.push(spacer());

    messages.forEach((msg, idx) => {
      const roleLabel = msg.role === "user" ? "You" : "Ora";
      children.push(h2(roleLabel));
      msg.content.split("\n").forEach((line) => {
        if (line.trim()) children.push(body(line));
        else children.push(spacer());
      });
      if (idx < messages.length - 1) children.push(spacer());
    });
  }

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  const blob = await Packer.toBlob(doc);
  triggerDownload(blob, sanitizeFilenameLocal(basename) + ".docx");
}
