import type { DatasetAnalysisResult } from "@/types/dataset-analysis";
import { sanitizeForExport } from "./sanitizer";
import { LIMITS } from "./size-limits";
import { triggerDownload, sanitizeFilenameLocal } from "./utils";

export type XlsxExportSource = {
  kind: "dataset";
  data: DatasetAnalysisResult;
  title?: string;
};

function addNoticeRowIfTruncated<T>(arr: T[], max: number): [T[], boolean] {
  if (arr.length <= max) return [arr, false];
  return [arr.slice(0, max), true];
}

export async function downloadXlsx(source: XlsxExportSource, basename: string): Promise<void> {
  const XLSX = await import("xlsx");

  const data = sanitizeForExport(source.data);
  const title = source.title ?? "Dataset Analysis Report";
  const dateGenerated = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const wb = XLSX.utils.book_new();

  // ─── Summary sheet ─────────────────────────────────────────────────────────
  const summaryRows: (string | number)[][] = [
    [title],
    [],
    ["Analysis Type", data.analysisType],
    ["Generated", dateGenerated],
    ["Generated By", "Ora AI"],
    [],
    ["Executive Summary"],
    [data.summary],
  ];
  if (data.datasetProfile) {
    summaryRows.push([]);
    summaryRows.push(["Dataset Profile"]);
    summaryRows.push(["Rows", data.datasetProfile.rowCount]);
    summaryRows.push(["Columns", data.datasetProfile.colCount]);
    if (data.datasetProfile.sheetName) {
      summaryRows.push(["Sheet", data.datasetProfile.sheetName]);
    }
    if (data.datasetProfile.truncated) {
      summaryRows.push(["Note", "Dataset was truncated before analysis"]);
    }
  }
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryRows);
  summarySheet["!cols"] = [{ wch: 22 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(wb, summarySheet, "Summary");

  // ─── KPI Results ───────────────────────────────────────────────────────────
  if (data.kpiGaps?.length) {
    const [rows, wasTruncated] = addNoticeRowIfTruncated(data.kpiGaps, LIMITS.maxXlsxRowsPerSheet);
    const kpiRows: (string | number)[][] = [
      ["Metric", "Current", "Target", "Gap", "Trend"],
      ...rows.map((k) => [k.metric, k.current, k.target ?? "", k.gap ?? "", k.trend ?? ""]),
    ];
    if (wasTruncated) {
      kpiRows.push([
        `[Truncated — only first ${LIMITS.maxXlsxRowsPerSheet} rows shown]`,
        "",
        "",
        "",
        "",
      ]);
    }
    const sheet = XLSX.utils.aoa_to_sheet(kpiRows);
    sheet["!cols"] = [{ wch: 30 }, { wch: 15 }, { wch: 15 }, { wch: 15 }, { wch: 15 }];
    XLSX.utils.book_append_sheet(wb, sheet, "KPI Results");
  }

  // ─── Findings ──────────────────────────────────────────────────────────────
  if (data.keyFindings?.length) {
    const [rows, wasTruncated] = addNoticeRowIfTruncated(data.keyFindings, LIMITS.maxFindings);
    const findingsRows: (string | number)[][] = [
      ["#", "Finding"],
      ...rows.map((f, i) => [i + 1, f]),
    ];
    if (wasTruncated) {
      findingsRows.push(["", `[Truncated — only first ${LIMITS.maxFindings} findings shown]`]);
    }
    const sheet = XLSX.utils.aoa_to_sheet(findingsRows);
    sheet["!cols"] = [{ wch: 5 }, { wch: 80 }];
    XLSX.utils.book_append_sheet(wb, sheet, "Findings");
  }

  // ─── Trends ────────────────────────────────────────────────────────────────
  if (data.trendFindings?.length) {
    const [rows] = addNoticeRowIfTruncated(data.trendFindings, LIMITS.maxTrendRows);
    const trendRows: string[][] = [
      ["Direction", "Description"],
      ...rows.map((t) => [t.direction ?? "", t.description]),
    ];
    const sheet = XLSX.utils.aoa_to_sheet(trendRows);
    sheet["!cols"] = [{ wch: 12 }, { wch: 80 }];
    XLSX.utils.book_append_sheet(wb, sheet, "Trends");
  }

  // ─── Root Cause ────────────────────────────────────────────────────────────
  if (data.rootCauseAnalysis || data.paretoFindings?.length) {
    const rcRows: (string | number)[][] = [];
    if (data.paretoFindings?.length) {
      rcRows.push(["Pareto Analysis"]);
      rcRows.push(["Category", "Value", "Cumulative %"]);
      const [rows] = addNoticeRowIfTruncated(data.paretoFindings, LIMITS.maxParetoRows);
      rows.forEach((p) => {
        rcRows.push([p.label, String(p.value), p.cumPct != null ? `${p.cumPct.toFixed(1)}%` : ""]);
      });
      rcRows.push([]);
    }
    if (data.rootCauseAnalysis) {
      const rca = data.rootCauseAnalysis;
      if (rca.likelyCauses?.length) {
        rcRows.push(["Likely Causes"]);
        rca.likelyCauses.forEach((c) => rcRows.push(["", c]));
        rcRows.push([]);
      }
      if (rca.fiveWhys?.length) {
        rcRows.push(["Five Whys"]);
        rca.fiveWhys.forEach((w, i) => rcRows.push([`Why ${i + 1}`, w]));
        rcRows.push([]);
      }
      if (rca.fishbone) {
        rcRows.push(["Fishbone — Cause Category", "Cause"]);
        for (const [category, causes] of Object.entries(rca.fishbone)) {
          causes.forEach((c) => rcRows.push([category, c]));
        }
      }
    }
    if (rcRows.length > 0) {
      const sheet = XLSX.utils.aoa_to_sheet(rcRows);
      sheet["!cols"] = [{ wch: 30 }, { wch: 60 }, { wch: 15 }];
      XLSX.utils.book_append_sheet(wb, sheet, "Root Cause");
    }
  }

  // ─── Action Plan ───────────────────────────────────────────────────────────
  if (data.actionPlan?.length) {
    const [rows, wasTruncated] = addNoticeRowIfTruncated(data.actionPlan, LIMITS.maxActionPlanRows);
    const apRows: string[][] = [
      ["Action", "Priority", "Owner", "Timeline"],
      ...rows.map((a) => [a.action, a.priority, a.owner ?? "", a.timeline ?? ""]),
    ];
    if (wasTruncated) {
      apRows.push([`[Truncated — only first ${LIMITS.maxActionPlanRows} rows shown]`, "", "", ""]);
    }
    const sheet = XLSX.utils.aoa_to_sheet(apRows);
    sheet["!cols"] = [{ wch: 50 }, { wch: 12 }, { wch: 20 }, { wch: 20 }];
    XLSX.utils.book_append_sheet(wb, sheet, "Action Plan");
  }

  // ─── Recommendations ───────────────────────────────────────────────────────
  if (data.recommendations?.length) {
    const [rows] = addNoticeRowIfTruncated(data.recommendations, LIMITS.maxRecommendations);
    const recRows: (string | number)[][] = [
      ["#", "Recommendation"],
      ...rows.map((r, i) => [i + 1, r]),
    ];
    const sheet = XLSX.utils.aoa_to_sheet(recRows);
    sheet["!cols"] = [{ wch: 5 }, { wch: 80 }];
    XLSX.utils.book_append_sheet(wb, sheet, "Recommendations");
  }

  // ─── Risk Matrix ───────────────────────────────────────────────────────────
  if (data.risksAndLimitations?.length) {
    const riskRows: (string | number)[][] = [
      ["#", "Risk / Limitation"],
      ...data.risksAndLimitations.map((r, i) => [i + 1, r]),
    ];
    const sheet = XLSX.utils.aoa_to_sheet(riskRows);
    sheet["!cols"] = [{ wch: 5 }, { wch: 80 }];
    XLSX.utils.book_append_sheet(wb, sheet, "Risk Matrix");
  }

  const buf = XLSX.write(wb, { bookType: "xlsx", type: "array" }) as ArrayBuffer;
  const blob = new Blob([buf], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  triggerDownload(blob, sanitizeFilenameLocal(basename) + ".xlsx");
}
