import type { OraMessage } from "@/hooks/use-ora-chat";
import type { DatasetAnalysisResult } from "@/types/dataset-analysis";
import type { ReportMetadata } from "./report-metadata";
import type { ReportTemplateId } from "./report-templates";
import { sanitizeForExport, sanitizeSummary, sanitizeTitle, truncateArray } from "./sanitizer";
import { LIMITS } from "./size-limits";
import { triggerDownload, sanitizeFilenameLocal } from "./utils";

export type PptxExportSource =
  | { kind: "dataset"; data: DatasetAnalysisResult; title?: string }
  | { kind: "message"; message: OraMessage; title?: string }
  | { kind: "conversation"; messages: OraMessage[]; title?: string };

const PPTX_MIME = "application/vnd.openxmlformats-officedocument.presentationml.presentation";

const C = {
  titleBg: "0F172A",
  accent: "2563EB",
  heading: "1E3A5F",
  body: "1E293B",
  muted: "64748B",
  footer: "94A3B8",
  white: "FFFFFF",
  lightBlue: "7DD3FC",
  tablHdr: "1E3A5F",
  tablHdrFg: "FFFFFF",
  tablRow0: "F8FAFC",
  tablRow1: "FFFFFF",
  border: "E2E8F0",
} as const;

function dateLabel(): string {
  return new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

export async function downloadPptx(
  source: PptxExportSource,
  basename: string,
  meta?: ReportMetadata,
  _templateId?: ReportTemplateId,
): Promise<void> {
  const { default: PptxGenJS } = await import("pptxgenjs");
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";

  const date = dateLabel();
  let slideCount = 0;

  // ── slide factory ────────────────────────────────────────────────────────
  const nextSlide = () => {
    if (slideCount >= LIMITS.maxPptxSlides) return null;
    slideCount++;
    return pptx.addSlide();
  };

  const addFooter = (s: ReturnType<typeof pptx.addSlide>) => {
    s.addText(`Confidential \u00B7 Generated by Ora AI \u00B7 MustaFlow`, {
      x: 0.3,
      y: 7.15,
      w: 12.73,
      h: 0.35,
      fontSize: 9,
      color: C.footer,
      align: "right",
    });
  };

  const addHeading = (s: ReturnType<typeof pptx.addSlide>, text: string) => {
    s.addText(text, {
      x: 0.5,
      y: 0.25,
      w: 12.33,
      h: 0.8,
      fontSize: 26,
      bold: true,
      color: C.heading,
    });
    // thin accent line rendered as a small filled text placeholder
    s.addText(" ", {
      x: 0.5,
      y: 1.1,
      w: 12.33,
      h: 0.06,
      fill: { color: C.accent },
      fontSize: 1,
      color: C.accent,
    });
  };

  // ── bullet / section slide ───────────────────────────────────────────────
  const addSection = (title: string, bullets: string[], numbered = false) => {
    const s = nextSlide();
    if (!s) return;
    addHeading(s, title);

    const items = truncateArray(bullets, LIMITS.maxPptxBullets);
    const textItems = items.map((b, i) => ({
      text: `${numbered ? `${i + 1}.  ` : "\u2022  "}${b}`,
      options: { breakLine: true, paraSpaceBefore: i === 0 ? 0 : 10 },
    }));

    s.addText(textItems, {
      x: 0.5,
      y: 1.25,
      w: 12.33,
      h: 5.65,
      fontSize: 15,
      color: C.body,
      valign: "top",
    });

    if (bullets.length > LIMITS.maxPptxBullets) {
      s.addText(`[\u2026 ${bullets.length - LIMITS.maxPptxBullets} more items — see full report]`, {
        x: 0.5,
        y: 7.0,
        w: 12.33,
        h: 0.25,
        fontSize: 9,
        color: C.footer,
        italic: true,
      });
    }

    addFooter(s);
  };

  // ── table slide ──────────────────────────────────────────────────────────
  const addTableSection = (title: string, headers: string[], rows: string[][], colW?: number[]) => {
    const s = nextSlide();
    if (!s) return;
    addHeading(s, title);

    const capped = truncateArray(rows, LIMITS.maxPptxTableRows);

    const makeRow = (cells: string[], isHeader: boolean, rowIdx: number) =>
      cells.map((text) => ({
        text,
        options: {
          bold: isHeader,
          fontSize: isHeader ? 13 : 12,
          color: isHeader ? C.tablHdrFg : C.body,
          fill: {
            color: isHeader ? C.tablHdr : rowIdx % 2 === 0 ? C.tablRow0 : C.tablRow1,
          },
          margin: [4, 6, 4, 6] as [number, number, number, number],
          valign: "middle" as const,
        },
      }));

    const tableRows = [
      makeRow(headers, true, 0),
      ...capped.map((row, i) => makeRow(row, false, i)),
    ];

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    s.addTable(tableRows as any, {
      x: 0.5,
      y: 1.25,
      w: 12.33,
      rowH: 0.38,
      ...(colW ? { colW } : {}),
      border: { type: "solid", pt: 0.5, color: C.border },
    });

    if (rows.length > LIMITS.maxPptxTableRows) {
      s.addText(
        `[Showing ${LIMITS.maxPptxTableRows} of ${rows.length} rows — full detail in Excel / Word export]`,
        { x: 0.5, y: 7.0, w: 12.33, h: 0.25, fontSize: 9, color: C.footer, italic: true },
      );
    }

    addFooter(s);
  };

  // ── title slide (dark) ───────────────────────────────────────────────────
  const addTitleSlide = (reportTitle: string, subtitle: string) => {
    const s = nextSlide();
    if (!s) return;
    s.background = { color: C.titleBg };

    s.addText(reportTitle, {
      x: 0.8,
      y: 2.1,
      w: 11.73,
      h: 1.6,
      fontSize: 40,
      bold: true,
      color: C.white,
      align: "center",
    });

    if (subtitle) {
      s.addText(subtitle, {
        x: 0.8,
        y: 3.8,
        w: 11.73,
        h: 0.65,
        fontSize: 18,
        color: C.lightBlue,
        align: "center",
      });
    }

    s.addText(`Generated by Ora AI \u00B7 MustaFlow \u00B7 ${date}`, {
      x: 0.8,
      y: 4.6,
      w: 11.73,
      h: 0.5,
      fontSize: 12,
      color: C.muted,
      align: "center",
    });
  };

  // ── executive summary slide ──────────────────────────────────────────────
  const addExecSummarySlide = (summary: string, topHighlights: string[]) => {
    const s = nextSlide();
    if (!s) return;
    addHeading(s, "Executive Summary");

    if (topHighlights.length > 0) {
      s.addText(summary, {
        x: 0.5,
        y: 1.25,
        w: 12.33,
        h: 2.85,
        fontSize: 14,
        color: C.body,
        valign: "top",
        wrap: true,
      });
      s.addText("Key Highlights", {
        x: 0.5,
        y: 4.15,
        w: 12.33,
        h: 0.45,
        fontSize: 14,
        bold: true,
        color: C.heading,
      });
      const hlItems = topHighlights.slice(0, 3).map((h, i) => ({
        text: `\u2022  ${h}`,
        options: { breakLine: true, paraSpaceBefore: i === 0 ? 0 : 8 },
      }));
      s.addText(hlItems, {
        x: 0.5,
        y: 4.65,
        w: 12.33,
        h: 2.2,
        fontSize: 14,
        color: C.body,
        valign: "top",
      });
    } else {
      s.addText(summary, {
        x: 0.5,
        y: 1.25,
        w: 12.33,
        h: 5.65,
        fontSize: 15,
        color: C.body,
        valign: "top",
        wrap: true,
      });
    }

    addFooter(s);
  };

  // ========================================================================
  // Build slides
  // ========================================================================

  if (source.kind === "dataset" || (source.kind === "message" && source.message.datasetResult)) {
    const raw = source.kind === "dataset" ? source.data : source.message.datasetResult!;
    const data = sanitizeForExport(raw);
    const inputTitle = source.kind === "dataset" ? source.title : source.title;
    const reportTitle = meta?.title ?? sanitizeTitle(inputTitle ?? "Dataset Analysis Report");
    const analysisType = data.analysisType
      .replace(/-/g, " ")
      .replace(/\b\w/g, (c) => c.toUpperCase());

    // 1. Title
    addTitleSlide(reportTitle, analysisType);

    // 2. Executive Summary
    const summary = sanitizeSummary(data.summary);
    addExecSummarySlide(summary, data.keyFindings?.slice(0, 3) ?? []);

    // 3. Key Findings
    if (data.keyFindings?.length) {
      addSection("Key Findings", data.keyFindings, true);
    }

    // 4. KPI Performance
    if (data.kpiGaps?.length) {
      const hdrs = ["Metric", "Current", "Target", "Gap", "Trend"];
      const rows = data.kpiGaps.map((k) => [
        k.metric,
        k.current,
        k.target ?? "\u2014",
        k.gap ?? "\u2014",
        k.trend ?? "\u2014",
      ]);
      addTableSection("KPI Performance", hdrs, rows, [3.5, 2.0, 2.0, 2.33, 2.5]);
    }

    // 5. Root Cause / Analysis
    if (data.rootCauseAnalysis?.likelyCauses?.length) {
      const items = [
        ...data.rootCauseAnalysis.likelyCauses.map((c) => `Root Cause: ${c}`),
        ...(data.rootCauseAnalysis.fiveWhys ?? []).slice(0, 3).map((w, i) => `Why ${i + 1}: ${w}`),
      ];
      addSection("Root Cause Analysis", items);
    } else if (data.trendFindings?.length) {
      const items = data.trendFindings.map(
        (t) => `[${(t.direction ?? "unknown").toUpperCase()}] ${t.description}`,
      );
      addSection("Trend Analysis", items);
    } else if (data.paretoFindings?.length) {
      const hdrs = ["Category", "Value", "Cumulative %"];
      const rows = data.paretoFindings.map((p) => [
        p.label,
        String(p.value),
        p.cumPct != null ? `${p.cumPct.toFixed(1)}%` : "\u2014",
      ]);
      addTableSection("Pareto Analysis", hdrs, rows, [5.5, 3.5, 3.33]);
    }

    // 6. Risks
    if (data.risksAndLimitations?.length) {
      addSection("Risks & Limitations", data.risksAndLimitations);
    }

    // 7. Key Opportunities (top half of recommendations)
    if (data.recommendations?.length) {
      const half = Math.ceil(data.recommendations.length / 2);
      addSection("Key Opportunities", data.recommendations.slice(0, half), true);
    }

    // 8. Recommendations (full list)
    if (data.recommendations?.length) {
      addSection("Recommendations", data.recommendations, true);
    }

    // 9. Action Plan
    if (data.actionPlan?.length) {
      const hdrs = ["Action", "Priority", "Owner", "Timeline"];
      const rows = data.actionPlan.map((a) => [
        a.action,
        a.priority,
        a.owner ?? "\u2014",
        a.timeline ?? "\u2014",
      ]);
      addTableSection("Action Plan", hdrs, rows, [5.83, 2.0, 2.0, 2.5]);
    }

    // 10. Next Steps / Timeline
    if (data.nextSteps?.length) {
      addSection("Next Steps", data.nextSteps);
    } else if (data.actionPlan?.length) {
      const highPri = data.actionPlan
        .filter((a) => a.priority === "high")
        .map((a) => a.action)
        .slice(0, 5);
      if (highPri.length) addSection("Next Steps", highPri);
    }
  } else if (source.kind === "message") {
    const msg = sanitizeForExport(source.message);
    const reportTitle = sanitizeTitle(source.title ?? "Ora Response");
    const roleLabel = msg.role === "user" ? "User" : "Ora";

    addTitleSlide(reportTitle, roleLabel);

    // Content slide
    const s = nextSlide();
    if (s) {
      addHeading(s, roleLabel);
      const lines = msg.content.split("\n").filter((l) => l.trim());
      const textItems = lines.slice(0, 20).map((l, i) => ({
        text: l,
        options: { breakLine: true, paraSpaceBefore: i === 0 ? 0 : 8 },
      }));
      s.addText(textItems, {
        x: 0.5,
        y: 1.25,
        w: 12.33,
        h: 5.65,
        fontSize: 15,
        color: C.body,
        valign: "top",
        wrap: true,
      });
      addFooter(s);
    }
  } else {
    // conversation
    const msgs = truncateArray(
      source.messages.map((m) => sanitizeForExport(m)),
      LIMITS.maxPptxSlides - 1,
    );
    const reportTitle = sanitizeTitle(source.title ?? "Ora Conversation");

    addTitleSlide(reportTitle, `${msgs.length} messages`);

    for (const msg of msgs) {
      const s = nextSlide();
      if (!s) break;
      const roleLabel = msg.role === "user" ? "You" : "Ora";
      addHeading(s, roleLabel);
      const lines = msg.content.split("\n").filter((l) => l.trim());
      const textItems = lines.slice(0, 15).map((l, i) => ({
        text: l,
        options: { breakLine: true, paraSpaceBefore: i === 0 ? 0 : 8 },
      }));
      s.addText(textItems, {
        x: 0.5,
        y: 1.25,
        w: 12.33,
        h: 5.65,
        fontSize: 14,
        color: C.body,
        valign: "top",
        wrap: true,
      });
      addFooter(s);
    }
  }

  // Write and download
  const output = await pptx.write({ outputType: "blob" });
  const blob =
    output instanceof Blob
      ? output
      : new Blob([output as unknown as ArrayBuffer], { type: PPTX_MIME });
  triggerDownload(blob, sanitizeFilenameLocal(basename) + ".pptx");
}
