import type { DatasetAnalysisResult } from "@/types/dataset-analysis";
import type { ReportMetadata } from "./report-metadata";
import type { ReportTemplateId } from "./report-templates";
import {
  buildAnalystChartSeries,
  calculationSuggestionRows,
  chartSuggestionRows,
  hasAnalystWorkflow,
  reportSuggestionRows,
} from "./analyst-workflow-export";
import { deriveKpiStatus, buildRoadmap } from "./report-metadata";
import { sanitizeForExport } from "./sanitizer";
import { LIMITS } from "./size-limits";
import { triggerDownload, sanitizeFilenameLocal } from "./utils";

export type XlsxExportSource = {
  kind: "dataset";
  data: DatasetAnalysisResult;
  title?: string;
};

function addNoticeRowIfTruncated<T>(arr: T[], max: number): [T[], boolean] {
  if (arr.length <= max) return [arr, false];
  return [arr.slice(0, max), true];
}

type Row = (string | number)[];
type ColSpec = { wch: number };

function addSheet(
  wb: import("exceljs").Workbook,
  name: string,
  rows: Row[],
  colWidths: ColSpec[],
): void {
  const ws = wb.addWorksheet(name);
  ws.addRows(rows);
  colWidths.forEach(({ wch }, i) => {
    ws.getColumn(i + 1).width = wch;
  });
}

export async function downloadXlsx(
  source: XlsxExportSource,
  basename: string,
  meta?: ReportMetadata,
  _templateId?: ReportTemplateId,
): Promise<void> {
  const ExcelJS = (await import("exceljs")).default;
  const wb = new ExcelJS.Workbook();

  const data = sanitizeForExport(source.data);
  const title = meta?.title ?? source.title ?? "Dataset Analysis Report";
  const dateGenerated =
    meta?.generatedDate ??
    new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

  if (meta) {
    const coverRows: Row[] = [
      [title],
      [],
      ["Report Type", meta.reportType],
      ["Company", meta.company || "Company / Organization"],
      ["Department", meta.department || "Department"],
      ["Generated", dateGenerated],
      ["Generated By", "Ora AI \u00B7 MustaFlow AI"],
      [],
      ...(meta.preparedFor ? [["Prepared For", meta.preparedFor] as Row] : []),
      ...(meta.preparedBy ? [["Prepared By", meta.preparedBy] as Row] : []),
      [],
      ["Analysis Type", data.analysisType],
    ];
    addSheet(wb, "Cover Page", coverRows, [{ wch: 18 }, { wch: 60 }]);
  }

  const summaryRows: Row[] = [
    [title],
    [],
    ["Analysis Type", data.analysisType],
    ["Generated", dateGenerated],
    ["Generated By", "Ora AI"],
    [],
    ["Executive Summary"],
    [data.summary],
  ];
  if (data.datasetProfile) {
    summaryRows.push([]);
    summaryRows.push(["Dataset Profile"]);
    summaryRows.push(["Rows", data.datasetProfile.rowCount]);
    summaryRows.push(["Columns", data.datasetProfile.colCount]);
    if (data.datasetProfile.sheetName) {
      summaryRows.push(["Sheet", data.datasetProfile.sheetName]);
    }
    if (data.datasetProfile.truncated) {
      summaryRows.push(["Note", "Dataset was truncated before analysis"]);
    }
  }
  addSheet(wb, "Summary", summaryRows, [{ wch: 22 }, { wch: 60 }]);

  if (data.kpiGaps?.length) {
    const [rows, wasTruncated] = addNoticeRowIfTruncated(data.kpiGaps, LIMITS.maxXlsxRowsPerSheet);
    const kpiRows: Row[] = [
      ["Metric", "Current", "Target", "Gap", "Status", "Trend"],
      ...rows.map((k) => [
        k.metric,
        k.current,
        k.target ?? "",
        k.gap ?? "",
        deriveKpiStatus(k),
        k.trend ?? "",
      ]),
    ];
    if (wasTruncated) {
      kpiRows.push([
        `[Truncated \u2014 only first ${LIMITS.maxXlsxRowsPerSheet} rows shown]`,
        "",
        "",
        "",
        "",
        "",
      ]);
    }
    addSheet(wb, "KPI Scorecard", kpiRows, [
      { wch: 30 },
      { wch: 15 },
      { wch: 15 },
      { wch: 15 },
      { wch: 18 },
      { wch: 12 },
    ]);
  }

  if (data.keyFindings?.length) {
    const [rows, wasTruncated] = addNoticeRowIfTruncated(data.keyFindings, LIMITS.maxFindings);
    const findingsRows: Row[] = [["#", "Finding"], ...rows.map((f, i) => [i + 1, f])];
    if (wasTruncated) {
      findingsRows.push(["", `[Truncated \u2014 only first ${LIMITS.maxFindings} findings shown]`]);
    }
    addSheet(wb, "Findings", findingsRows, [{ wch: 5 }, { wch: 80 }]);
  }

  if (data.trendFindings?.length) {
    const [rows] = addNoticeRowIfTruncated(data.trendFindings, LIMITS.maxTrendRows);
    const trendRows: Row[] = [
      ["Direction", "Description"],
      ...rows.map((t) => [t.direction ?? "", t.description]),
    ];
    addSheet(wb, "Trends", trendRows, [{ wch: 12 }, { wch: 80 }]);
  }

  if (data.rootCauseAnalysis || data.paretoFindings?.length) {
    const rcRows: Row[] = [];
    if (data.paretoFindings?.length) {
      rcRows.push(["Pareto Analysis"]);
      rcRows.push(["Category", "Value", "Cumulative %"]);
      const [rows] = addNoticeRowIfTruncated(data.paretoFindings, LIMITS.maxParetoRows);
      rows.forEach((p) => {
        rcRows.push([p.label, String(p.value), p.cumPct != null ? `${p.cumPct.toFixed(1)}%` : ""]);
      });
      rcRows.push([]);
    }
    if (data.rootCauseAnalysis) {
      const rca = data.rootCauseAnalysis;
      if (rca.likelyCauses?.length) {
        rcRows.push(["Likely Causes"]);
        rca.likelyCauses.forEach((c) => rcRows.push(["", c]));
        rcRows.push([]);
      }
      if (rca.fiveWhys?.length) {
        rcRows.push(["Five Whys"]);
        rca.fiveWhys.forEach((w, i) => rcRows.push([`Why ${i + 1}`, w]));
        rcRows.push([]);
      }
      if (rca.fishbone) {
        rcRows.push(["Fishbone \u2014 Cause Category", "Cause"]);
        for (const [category, causes] of Object.entries(rca.fishbone)) {
          causes.forEach((c) => rcRows.push([category, c]));
        }
      }
    }
    if (rcRows.length > 0) {
      addSheet(wb, "Root Cause", rcRows, [{ wch: 30 }, { wch: 60 }, { wch: 15 }]);
    }
  }

  if (data.actionPlan?.length) {
    const [rows, wasTruncated] = addNoticeRowIfTruncated(data.actionPlan, LIMITS.maxActionPlanRows);
    const apRows: Row[] = [
      ["Action", "Priority", "Owner", "Timeline"],
      ...rows.map((a) => [a.action, a.priority, a.owner ?? "", a.timeline ?? ""]),
    ];
    if (wasTruncated) {
      apRows.push([
        `[Truncated \u2014 only first ${LIMITS.maxActionPlanRows} rows shown]`,
        "",
        "",
        "",
      ]);
    }
    addSheet(wb, "Action Plan", apRows, [{ wch: 50 }, { wch: 12 }, { wch: 20 }, { wch: 20 }]);
  }

  const generatedCharts = buildAnalystChartSeries(data);
  if (generatedCharts.length) {
    const chartRows: Row[] = [["Chart", "Label", "Value"]];
    generatedCharts.forEach((series) => {
      series.labels.forEach((label, index) => {
        chartRows.push([series.title, label, series.values[index] ?? 0]);
      });
    });
    addSheet(wb, "Generated Charts", chartRows, [{ wch: 30 }, { wch: 34 }, { wch: 16 }]);
  }

  if (data.actionPlan?.length) {
    const pmRows: Row[] = [["Priority Matrix"], []];
    const high = data.actionPlan.filter((a) => a.priority === "high");
    const medium = data.actionPlan.filter((a) => a.priority === "medium");
    const low = data.actionPlan.filter((a) => a.priority === "low");

    const addGroup = (label: string, items: typeof high) => {
      if (!items.length) return;
      pmRows.push([label]);
      pmRows.push(["Action", "Impact", "Estimated Effort", "Owner", "Timeline"]);
      items
        .slice(0, LIMITS.maxPriorityMatrixRows)
        .forEach((a) =>
          pmRows.push([
            a.action,
            a.priority === "high" ? "High" : a.priority === "medium" ? "Medium" : "Low",
            "Estimated Medium",
            a.owner ?? "",
            a.timeline ?? "",
          ]),
        );
      pmRows.push([]);
    };

    addGroup("High Priority \u2014 Immediate Action Required", high);
    addGroup("Medium Priority \u2014 Short-term Action", medium);
    addGroup("Lower Priority \u2014 Monitor / Consider", low);

    addSheet(wb, "Priority Matrix", pmRows, [
      { wch: 50 },
      { wch: 12 },
      { wch: 20 },
      { wch: 20 },
      { wch: 18 },
    ]);
  }

  if (data.actionPlan?.length || data.nextSteps?.length) {
    const roadmap = buildRoadmap(data.actionPlan, data.nextSteps);
    const rmRows: Row[] = [["Improvement Roadmap"], [], ["Timeframe", "Action", "Priority"]];

    const addPhase = (label: string, items: string[], priority: string) =>
      items.slice(0, LIMITS.maxRoadmapItems).forEach((a) => rmRows.push([label, a, priority]));

    addPhase("Immediate (0\u201330 Days)", roadmap.immediate, "High");
    addPhase("Short-term (30\u201360 Days)", roadmap.thirtyDay, "Medium");
    addPhase("Medium-term (60\u201390 Days)", roadmap.sixtyDay, "Low");
    addPhase("Strategic (90+ Days)", roadmap.ninetyPlus, "Strategic");

    if (rmRows.length > 3) {
      addSheet(wb, "Improvement Roadmap", rmRows, [{ wch: 28 }, { wch: 55 }, { wch: 12 }]);
    }
  }

  if (data.recommendations?.length) {
    const [rows] = addNoticeRowIfTruncated(data.recommendations, LIMITS.maxRecommendations);
    const recRows: Row[] = [["#", "Recommendation"], ...rows.map((r, i) => [i + 1, r])];
    addSheet(wb, "Recommendations", recRows, [{ wch: 5 }, { wch: 80 }]);
  }

  if (data.risksAndLimitations?.length) {
    const riskRows: Row[] = [
      ["#", "Risk / Limitation"],
      ...data.risksAndLimitations.map((r, i) => [i + 1, r]),
    ];
    addSheet(wb, "Risk Matrix", riskRows, [{ wch: 5 }, { wch: 80 }]);
  }

  if (data.healthScore) {
    const hs = data.healthScore;
    const hsRows: Row[] = [
      ["Overall Health Score"],
      [],
      ["Score", hs.score],
      ["Category", hs.category],
      ["Explanation", hs.explanation],
    ];
    addSheet(wb, "Health Score", hsRows, [{ wch: 18 }, { wch: 70 }]);
  }

  if (data.financialImpact) {
    const fi = data.financialImpact;
    const fiRows: Row[] = [["Financial Impact Assessment"], [], ["Confidence", fi.confidence], []];
    if (fi.costOfIssues) fiRows.push(["Cost of Current Issues", fi.costOfIssues]);
    if (fi.savingsOpportunity) fiRows.push(["Savings Opportunity", fi.savingsOpportunity]);
    if (fi.revenueOpportunity) fiRows.push(["Revenue Opportunity", fi.revenueOpportunity]);
    if (fi.wasteReduction) fiRows.push(["Waste Reduction", fi.wasteReduction]);
    if (fi.notes) {
      fiRows.push([]);
      fiRows.push(["Notes", fi.notes]);
    }
    addSheet(wb, "Financial Impact", fiRows, [{ wch: 28 }, { wch: 65 }]);
  }

  if (data.operationalImpact) {
    const oi = data.operationalImpact;
    const oiRows: Row[] = [
      ["Operational Impact Assessment"],
      [],
      ["Overall Level", oi.overallLevel],
      ...(oi.summary ? [["Summary", oi.summary] as Row] : []),
      [],
      ["Dimension", "Level", "Explanation"],
    ];
    const dims: [string, typeof oi.productivity][] = [
      ["Productivity", oi.productivity],
      ["Throughput", oi.throughput],
      ["Downtime", oi.downtime],
      ["Labor", oi.labor],
      ["Quality", oi.quality],
      ["Capacity", oi.capacity],
    ];
    dims.filter(([, d]) => d).forEach(([name, d]) => oiRows.push([name, d!.level, d!.explanation]));
    addSheet(wb, "Operational Impact", oiRows, [{ wch: 18 }, { wch: 12 }, { wch: 65 }]);
  }

  if (data.customerImpact) {
    const ci = data.customerImpact;
    const ciRows: Row[] = [
      ["Customer Impact Assessment"],
      [],
      ["Overall Level", ci.overallLevel],
      ...(ci.summary ? [["Summary", ci.summary] as Row] : []),
      [],
      ["Dimension", "Level", "Explanation"],
    ];
    const cdims: [string, typeof ci.experience][] = [
      ["Customer Experience", ci.experience],
      ["Service", ci.service],
      ["Delivery", ci.delivery],
      ["Product Quality", ci.productQuality],
      ["Reputation", ci.reputation],
    ];
    cdims
      .filter(([, d]) => d)
      .forEach(([name, d]) => ciRows.push([name, d!.level, d!.explanation]));
    addSheet(wb, "Customer Impact", ciRows, [{ wch: 22 }, { wch: 12 }, { wch: 65 }]);
  }

  if (data.enhancedRecommendations?.length) {
    const erRows: Row[] = [
      [
        "Recommendation",
        "Priority",
        "Impact Score",
        "Effort Score",
        "Confidence Score",
        "Expected Benefit",
        "Timeline",
        "Difficulty",
        "Confidence",
      ],
      ...data.enhancedRecommendations.map((r) => [
        r.recommendation,
        r.priority,
        r.impactScore,
        r.effortScore,
        r.confidenceScore,
        r.expectedBenefit,
        r.timeline,
        r.difficulty,
        r.confidence,
      ]),
    ];
    addSheet(wb, "Enhanced Recommendations", erRows, [
      { wch: 50 },
      { wch: 10 },
      { wch: 12 },
      { wch: 12 },
      { wch: 16 },
      { wch: 45 },
      { wch: 16 },
      { wch: 12 },
      { wch: 12 },
    ]);
  }

  if (data.strategicRoadmap) {
    const sr = data.strategicRoadmap;
    const srRows: Row[] = [["Timeframe", "Action", "Owner", "Expected Outcome", "Priority"]];
    const addPhase = (label: string, items: typeof sr.immediate) =>
      items.forEach((item) =>
        srRows.push([label, item.action, item.owner ?? "", item.expectedOutcome, item.priority]),
      );
    addPhase("Immediate (0\u201330 Days)", sr.immediate);
    addPhase("Short-term (30\u201360 Days)", sr.shortTerm);
    addPhase("Medium-term (60\u201390 Days)", sr.mediumTerm);
    addPhase("Strategic (90+ Days)", sr.strategic);
    if (srRows.length > 1) {
      addSheet(wb, "Strategic Roadmap", srRows, [
        { wch: 24 },
        { wch: 48 },
        { wch: 20 },
        { wch: 45 },
        { wch: 12 },
      ]);
    }
  }

  if (data.enhancedRisks?.length) {
    const eriskRows: Row[] = [
      ["Risk", "Risk Score", "Level", "Probability", "Impact", "Mitigation"],
      ...data.enhancedRisks.map((r) => [
        r.risk,
        r.riskScore,
        r.riskLevel,
        r.probability,
        r.impact,
        r.mitigation,
      ]),
    ];
    addSheet(wb, "Risk Assessment", eriskRows, [
      { wch: 45 },
      { wch: 12 },
      { wch: 12 },
      { wch: 14 },
      { wch: 14 },
      { wch: 50 },
    ]);
  }

  if (hasAnalystWorkflow(data) && data.analystWorkflow) {
    const workflow = data.analystWorkflow;
    const chartRows = chartSuggestionRows(workflow);
    const calcRows = calculationSuggestionRows(workflow);
    const reportRows = reportSuggestionRows(workflow);

    if (chartRows.length) {
      addSheet(
        wb,
        "Suggested Charts",
        [["Title", "Type", "X Column", "Y Column", "Group By", "Reason"], ...chartRows],
        [{ wch: 32 }, { wch: 14 }, { wch: 18 }, { wch: 18 }, { wch: 18 }, { wch: 60 }],
      );
    }

    if (calcRows.length) {
      addSheet(
        wb,
        "Repeatable Calculations",
        [["Label", "Expression", "Description", "Columns"], ...calcRows],
        [{ wch: 28 }, { wch: 32 }, { wch: 64 }, { wch: 32 }],
      );
    }

    if (reportRows.length) {
      addSheet(
        wb,
        "Report Outputs",
        [["Format", "Title", "Description"], ...reportRows],
        [{ wch: 14 }, { wch: 34 }, { wch: 70 }],
      );
    }
  }

  const buf = await wb.xlsx.writeBuffer();
  const blob = new Blob([buf], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  triggerDownload(blob, sanitizeFilenameLocal(basename) + ".xlsx");
}
