export const LIMITS = {
  titleMaxChars: 200,
  summaryMaxChars: 3_000,
  maxFindings: 20,
  maxRecommendations: 20,
  maxActionPlanRows: 30,
  maxXlsxRowsPerSheet: 5_000,
  maxJsonExportBytes: 2_000_000,
  maxDocxSections: 50,
  maxKpiRows: 50,
  maxParetoRows: 50,
  maxTrendRows: 30,
  maxPptxBullets: 10,
  maxPptxTableRows: 12,
  maxPptxSlides: 20,
  maxRoadmapItems: 10,
  maxPriorityMatrixRows: 20,
  maxOpportunities: 10,
} as const;
