/**
 * report-print-template.tsx
 * Builds the complete HTML string for browser-native PDF/print generation.
 * Pure function — no React rendering, no DOM access. Returns a raw HTML string
 * for injection into a hidden iframe before window.print() is called.
 */

import type { DatasetAnalysisResult } from "@/types/dataset-analysis";
import type { ReportMetadata } from "@/lib/file-generation/report-metadata";
import type { ReportTemplateId, ReportSectionId } from "@/lib/file-generation/report-templates";
import {
  deriveKpiStatus,
  deriveRiskLevel,
  buildRoadmap,
} from "@/lib/file-generation/report-metadata";
import { getTemplate } from "@/lib/file-generation/report-templates";
import { sanitizeSummary, truncateArray } from "@/lib/file-generation/sanitizer";
import { LIMITS } from "@/lib/file-generation/size-limits";
import { PRINT_CSS } from "@/lib/file-generation/print-styles";

// ── HTML escape helper ──────────────────────────────────────────────────────
function esc(s: unknown): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// ── Element builders ────────────────────────────────────────────────────────
function h2(text: string): string {
  return `<h2>${esc(text)}</h2>`;
}

function h3(text: string): string {
  return `<h3>${esc(text)}</h3>`;
}

function p(text: string): string {
  return `<p>${esc(text)}</p>`;
}

function ul(items: string[]): string {
  return `<ul>${items.map((i) => `<li>${esc(i)}</li>`).join("")}</ul>`;
}

function ol(items: string[]): string {
  return `<ol>${items.map((i) => `<li>${esc(i)}</li>`).join("")}</ol>`;
}

function sec(content: string): string {
  return `<section>${content}</section>`;
}

function simpleTable(headers: string[], rows: string[][]): string {
  const ths = headers.map((h) => `<th>${esc(h)}</th>`).join("");
  const trs = rows
    .map((row) => `<tr>${row.map((cell) => `<td>${esc(cell)}</td>`).join("")}</tr>`)
    .join("\n");
  return `<table><thead><tr>${ths}</tr></thead><tbody>${trs}</tbody></table>`;
}

// ── Cover page ──────────────────────────────────────────────────────────────
function buildCoverPage(meta: ReportMetadata, reportTitle: string, reportType: string): string {
  const date =
    meta.generatedDate ??
    new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const metaRow = (label: string, value: string) =>
    value
      ? `<div class="cover-meta-row"><span class="cover-meta-label">${esc(label)}</span><span class="cover-meta-value">${esc(value)}</span></div>`
      : "";

  return `<div class="cover">
  <div class="cover-accent"></div>
  <div class="cover-title">${esc(reportTitle)}</div>
  <div class="cover-type">${esc(reportType)}</div>
  <hr class="cover-rule">
  <div class="cover-meta">
    ${metaRow("Company", meta.company ?? "")}
    ${metaRow("Department", meta.department ?? "")}
    ${metaRow("Generated", date)}
    ${metaRow("Prepared For", meta.preparedFor ?? "")}
    ${metaRow("Prepared By", meta.preparedBy ?? "")}
  </div>
  <div class="cover-footer">Generated by Ora AI &middot; MustaFlow AI</div>
</div>`;
}

// ── Dataset report sections ─────────────────────────────────────────────────
function buildDatasetHtml(
  data: DatasetAnalysisResult,
  meta: ReportMetadata | undefined,
  templateId: ReportTemplateId | undefined,
  reportTitle: string,
): string {
  const visibleSections = templateId
    ? new Set<ReportSectionId>(getTemplate(templateId).sections)
    : null;
  const show = (s: ReportSectionId) => !visibleSections || visibleSections.has(s);

  const analysisType = data.analysisType
    .replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());

  const date =
    meta?.generatedDate ??
    new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const parts: string[] = [];

  parts.push(`<div class="content">
<div class="report-header">
  <h1>${esc(reportTitle)}</h1>
  <div class="report-meta-line">Analysis Type: ${esc(analysisType)} &nbsp;&middot;&nbsp; ${esc(date)} &nbsp;&middot;&nbsp; Generated by Ora AI</div>
</div>`);

  // Executive Summary
  if (show("executive-summary")) {
    const lines = sanitizeSummary(data.summary)
      .split("\n")
      .map((l) => (l.trim() ? p(l) : '<div class="spacer"></div>'))
      .join("");
    parts.push(sec(h2("Executive Summary") + lines));
  }

  // Management Summary
  if (show("management-summary") && data.summary) {
    const firstSentence = data.summary.split(/[.!?]/)[0]?.trim() ?? data.summary.slice(0, 180);
    const why =
      data.rootCauseAnalysis?.likelyCauses?.[0] ??
      data.keyFindings?.[0] ??
      "See Key Findings section.";
    const impact = data.risksAndLimitations?.[0] ?? "See Risks section.";
    const riskLevel = deriveRiskLevel(data.risksAndLimitations?.length ?? 0);
    const action =
      data.actionPlan?.find((a) => a.priority === "high")?.action ??
      data.recommendations?.[0] ??
      "See Recommendations section.";

    parts.push(
      sec(
        h2("Management Summary") +
          simpleTable(
            ["Category", "Detail"],
            [
              ["What Happened", firstSentence + "."],
              ["Why It Happened", why],
              ["Operational Impact", impact],
              ["Risk Level", riskLevel],
              ["Recommended Action", action],
            ],
          ),
      ),
    );
  }

  // Key Findings
  if (show("key-findings") && data.keyFindings?.length) {
    parts.push(sec(h2("Key Findings") + ol(truncateArray(data.keyFindings, LIMITS.maxFindings))));
  }

  // KPI Scorecard — custom rendering for Status column CSS classes
  if (show("kpi-scorecard") && data.kpiGaps?.length) {
    const ths = ["Metric", "Current", "Target", "Gap", "Status", "Trend"]
      .map((h) => `<th>${esc(h)}</th>`)
      .join("");
    const trs = truncateArray(data.kpiGaps, LIMITS.maxKpiRows)
      .map((k) => {
        const status = deriveKpiStatus(k);
        const statusCls =
          status === "Immediate Action"
            ? "status-immediate"
            : status === "Monitor"
              ? "status-monitor"
              : "status-on-target";
        const trendCls =
          k.trend === "up" ? "trend-up" : k.trend === "down" ? "trend-down" : "trend-flat";
        return `<tr>
          <td>${esc(k.metric)}</td>
          <td>${esc(k.current)}</td>
          <td>${esc(k.target ?? "")}</td>
          <td>${esc(k.gap ?? "")}</td>
          <td class="${statusCls}">${esc(status)}</td>
          <td class="${trendCls}">${esc(k.trend ?? "")}</td>
        </tr>`;
      })
      .join("\n");
    parts.push(
      sec(
        h2("KPI Scorecard") + `<table><thead><tr>${ths}</tr></thead><tbody>${trs}</tbody></table>`,
      ),
    );
  }

  // Trend Analysis
  if (show("trend-analysis") && data.trendFindings?.length) {
    const rows = truncateArray(data.trendFindings, LIMITS.maxTrendRows).map((t) => [
      t.direction ? `[${t.direction.toUpperCase()}]` : "",
      t.description,
    ]);
    parts.push(sec(h2("Trend Analysis") + simpleTable(["Direction", "Finding"], rows)));
  }

  // Pareto Analysis
  if (show("pareto-analysis") && data.paretoFindings?.length) {
    const rows = truncateArray(data.paretoFindings, LIMITS.maxParetoRows).map((pf) => [
      pf.label,
      String(pf.value),
      pf.cumPct != null ? `${pf.cumPct.toFixed(1)}%` : "",
    ]);
    parts.push(
      sec(h2("Pareto Analysis") + simpleTable(["Category", "Value", "Cumulative %"], rows)),
    );
  }

  // Root Cause Analysis
  if (show("root-cause") && data.rootCauseAnalysis) {
    const rca = data.rootCauseAnalysis;
    let content = h2("Root Cause Analysis");
    if (rca.likelyCauses?.length) content += h3("Likely Causes") + ul(rca.likelyCauses);
    if (rca.fiveWhys?.length) content += h3("Five Whys") + ol(rca.fiveWhys);
    if (rca.fishbone && Object.keys(rca.fishbone).length > 0) {
      content += h3("Fishbone — Cause Categories");
      for (const [category, causes] of Object.entries(rca.fishbone)) {
        content += `<p><strong>${esc(category)}</strong></p>` + ul(causes);
      }
    }
    parts.push(sec(content));
  }

  // Risks & Limitations
  if (show("risks") && data.risksAndLimitations?.length) {
    parts.push(sec(h2("Risks & Limitations") + ul(data.risksAndLimitations)));
  }

  // Key Opportunities
  if (show("opportunities") && data.recommendations?.length) {
    const opps = data.recommendations.slice(0, LIMITS.maxOpportunities);
    parts.push(
      sec(
        h2("Key Opportunities") +
          p(
            "Based on the analysis, the following opportunities have been identified to drive improvement:",
          ) +
          ol(opps),
      ),
    );
  }

  // Recommendations
  if (show("recommendations") && data.recommendations?.length) {
    parts.push(
      sec(
        h2("Recommendations") + ol(truncateArray(data.recommendations, LIMITS.maxRecommendations)),
      ),
    );
  }

  // Action Plan
  if (show("action-plan") && data.actionPlan?.length) {
    const rows = truncateArray(data.actionPlan, LIMITS.maxActionPlanRows).map((a) => [
      a.action,
      a.priority,
      a.owner ?? "",
      a.timeline ?? "",
    ]);
    parts.push(
      sec(h2("Action Plan") + simpleTable(["Action", "Priority", "Owner", "Timeline"], rows)),
    );
  }

  // Priority Matrix
  if (show("priority-matrix") && data.actionPlan?.length) {
    const high = data.actionPlan.filter((a) => a.priority === "high");
    const medium = data.actionPlan.filter((a) => a.priority === "medium");
    const low = data.actionPlan.filter((a) => a.priority === "low");
    const formatItem = (a: (typeof data.actionPlan)[number]) =>
      `${a.action}${a.owner ? `  (Owner: ${a.owner})` : ""}${a.timeline ? `  ·  ${a.timeline}` : ""}`;

    let content = h2("Priority Action Matrix");
    if (high.length)
      content += h3("High Priority \u2014 Immediate Action Required") + ul(high.map(formatItem));
    if (medium.length)
      content += h3("Medium Priority \u2014 Short-term Action") + ul(medium.map(formatItem));
    if (low.length)
      content += h3("Lower Priority \u2014 Monitor / Consider") + ul(low.map(formatItem));
    parts.push(sec(content));
  }

  // Improvement Roadmap
  if (show("improvement-roadmap") && (data.actionPlan?.length || data.nextSteps?.length)) {
    const roadmap = buildRoadmap(data.actionPlan, data.nextSteps);
    const roadmapRows: string[][] = [];
    roadmap.immediate
      .slice(0, LIMITS.maxRoadmapItems)
      .forEach((a) => roadmapRows.push(["Immediate (0\u201330 Days)", a, "High"]));
    roadmap.thirtyDay
      .slice(0, LIMITS.maxRoadmapItems)
      .forEach((a) => roadmapRows.push(["Short-term (30\u201360 Days)", a, "Medium"]));
    roadmap.sixtyDay
      .slice(0, LIMITS.maxRoadmapItems)
      .forEach((a) => roadmapRows.push(["Medium-term (60\u201390 Days)", a, "Low"]));
    roadmap.ninetyPlus.forEach((a) => roadmapRows.push(["Strategic (90+ Days)", a, "Strategic"]));
    if (roadmapRows.length > 0) {
      parts.push(
        sec(
          h2("Improvement Roadmap") + simpleTable(["Timeframe", "Action", "Priority"], roadmapRows),
        ),
      );
    }
  }

  // Next Steps
  if (show("next-steps") && data.nextSteps?.length) {
    parts.push(sec(h2("Next Steps") + ul(data.nextSteps)));
  }

  // Health Score
  if (show("health-score") && data.healthScore) {
    const hs = data.healthScore;
    parts.push(
      sec(
        h2("Overall Health Score") +
          simpleTable(
            ["Category", "Detail"],
            [
              ["Score", `${hs.score}/100`],
              ["Rating", hs.category],
              ["Assessment", hs.explanation],
            ],
          ),
      ),
    );
  }

  // Why This Matters
  if (show("why-this-matters") && data.whyThisMatters) {
    const wtm = data.whyThisMatters;
    const wtmRows: string[][] = [
      ["Leadership Rationale", wtm.leadershipRationale],
      ["Consequences of Inaction", wtm.consequencesOfInaction],
      ["Strategic Implications", wtm.strategicImplications],
    ];
    if (wtm.competitiveImplications) {
      wtmRows.push(["Competitive Implications", wtm.competitiveImplications]);
    }
    parts.push(sec(h2("Why This Matters") + simpleTable(["Dimension", "Detail"], wtmRows)));
  }

  // Financial Impact
  if (show("financial-impact") && data.financialImpact) {
    const fi = data.financialImpact;
    const fiRows: string[][] = [["Confidence Level", fi.confidence]];
    if (fi.costOfIssues) fiRows.push(["Cost of Current Issues", fi.costOfIssues]);
    if (fi.savingsOpportunity) fiRows.push(["Savings Opportunity", fi.savingsOpportunity]);
    if (fi.revenueOpportunity) fiRows.push(["Revenue Opportunity", fi.revenueOpportunity]);
    if (fi.wasteReduction) fiRows.push(["Waste Reduction", fi.wasteReduction]);
    if (fi.notes) fiRows.push(["Notes", fi.notes]);
    parts.push(
      sec(h2("Financial Impact Assessment") + simpleTable(["Category", "Estimate"], fiRows)),
    );
  }

  // Operational Impact
  if (show("operational-impact") && data.operationalImpact) {
    const oi = data.operationalImpact;
    const oiRows: string[][] = [["Overall Level", oi.overallLevel]];
    if (oi.summary) oiRows.push(["Summary", oi.summary]);
    const oiDims: [string, typeof oi.productivity][] = [
      ["Productivity", oi.productivity],
      ["Throughput", oi.throughput],
      ["Downtime", oi.downtime],
      ["Labor", oi.labor],
      ["Quality", oi.quality],
      ["Capacity", oi.capacity],
    ];
    oiDims
      .filter(([, d]) => d !== undefined)
      .forEach(([name, d]) => oiRows.push([name, `${d!.level} \u2014 ${d!.explanation}`]));
    parts.push(
      sec(h2("Operational Impact Assessment") + simpleTable(["Dimension", "Assessment"], oiRows)),
    );
  }

  // Customer Impact
  if (show("customer-impact") && data.customerImpact) {
    const ci = data.customerImpact;
    const ciRows: string[][] = [["Overall Level", ci.overallLevel]];
    if (ci.summary) ciRows.push(["Summary", ci.summary]);
    const ciDims: [string, typeof ci.experience][] = [
      ["Customer Experience", ci.experience],
      ["Service", ci.service],
      ["Delivery", ci.delivery],
      ["Product Quality", ci.productQuality],
      ["Reputation", ci.reputation],
    ];
    ciDims
      .filter(([, d]) => d !== undefined)
      .forEach(([name, d]) => ciRows.push([name, `${d!.level} \u2014 ${d!.explanation}`]));
    parts.push(
      sec(h2("Customer Impact Assessment") + simpleTable(["Dimension", "Assessment"], ciRows)),
    );
  }

  // Enhanced Recommendations
  if (show("enhanced-recommendations") && data.enhancedRecommendations?.length) {
    const erRows = truncateArray(data.enhancedRecommendations, LIMITS.maxRecommendations).map(
      (r) => [
        r.recommendation,
        r.priority,
        `${r.impactScore}`,
        `${r.effortScore}`,
        `${r.confidenceScore}`,
        r.expectedBenefit,
        r.timeline,
        r.difficulty,
      ],
    );
    parts.push(
      sec(
        h2("Prioritized Recommendations") +
          simpleTable(
            [
              "Recommendation",
              "Priority",
              "Impact",
              "Effort",
              "Conf.",
              "Expected Benefit",
              "Timeline",
              "Difficulty",
            ],
            erRows,
          ),
      ),
    );
  }

  // Strategic Roadmap
  if (show("strategic-roadmap") && data.strategicRoadmap) {
    const sr = data.strategicRoadmap;
    const srRows: string[][] = [];
    const addSrPhase = (label: string, items: typeof sr.immediate) =>
      items.forEach((item) =>
        srRows.push([label, item.action, item.owner ?? "", item.expectedOutcome, item.priority]),
      );
    addSrPhase("Immediate (0\u201330 Days)", sr.immediate);
    addSrPhase("Short-term (30\u201360 Days)", sr.shortTerm);
    addSrPhase("Medium-term (60\u201390 Days)", sr.mediumTerm);
    addSrPhase("Strategic (90+ Days)", sr.strategic);
    if (srRows.length > 0) {
      parts.push(
        sec(
          h2("Strategic Roadmap") +
            simpleTable(["Timeframe", "Action", "Owner", "Expected Outcome", "Priority"], srRows),
        ),
      );
    }
  }

  // Enhanced Risks
  if (show("enhanced-risks") && data.enhancedRisks?.length) {
    const eriskRows = truncateArray(data.enhancedRisks, 10).map((r) => [
      r.risk,
      `${r.riskScore}/100`,
      r.riskLevel,
      r.probability,
      r.impact,
      r.mitigation,
    ]);
    parts.push(
      sec(
        h2("Risk Assessment") +
          simpleTable(["Risk", "Score", "Level", "Probability", "Impact", "Mitigation"], eriskRows),
      ),
    );
  }

  parts.push("</div>");
  return parts.join("\n");
}

// ── Message / conversation bodies ───────────────────────────────────────────
function buildMessageBody(
  content: string,
  role: string,
  meta: ReportMetadata | undefined,
  reportTitle: string,
): string {
  const date =
    meta?.generatedDate ??
    new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const roleLabel = role === "user" ? "User" : "Ora";
  const bodyHtml = content
    .split("\n")
    .map((line) => (line.trim() ? p(line) : '<div class="spacer"></div>'))
    .join("\n");
  return `<div class="content">
<div class="report-header">
  <h1>${esc(reportTitle)}</h1>
  <div class="report-meta-line">${esc(date)} &nbsp;&middot;&nbsp; Generated by Ora AI</div>
</div>
${sec(h2(roleLabel) + bodyHtml)}
</div>`;
}

function buildConversationBody(
  messages: Array<{ role: string; content: string }>,
  meta: ReportMetadata | undefined,
  reportTitle: string,
): string {
  const date =
    meta?.generatedDate ??
    new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const messagesHtml = messages
    .map((msg) => {
      const roleLabel = msg.role === "user" ? "User" : "Ora";
      const bodyHtml = msg.content
        .split("\n")
        .map((line) => (line.trim() ? p(line) : '<div class="spacer"></div>'))
        .join("\n");
      return sec(h2(roleLabel) + bodyHtml);
    })
    .join("\n");
  return `<div class="content">
<div class="report-header">
  <h1>${esc(reportTitle)}</h1>
  <div class="report-meta-line">${esc(date)} &nbsp;&middot;&nbsp; Generated by Ora AI</div>
</div>
${messagesHtml}
</div>`;
}

// ── Public interface ────────────────────────────────────────────────────────
export interface PrintTemplateOptions {
  data?: DatasetAnalysisResult;
  messages?: Array<{ role: string; content: string }>;
  meta?: ReportMetadata;
  templateId?: ReportTemplateId;
  reportTitle: string;
  reportType: string;
}

export function buildPrintHtml(opts: PrintTemplateOptions): string {
  const { data, messages, meta, templateId, reportTitle, reportType } = opts;

  const coverHtml = meta ? buildCoverPage(meta, reportTitle, reportType) : "";

  let bodyHtml: string;
  if (data) {
    bodyHtml = buildDatasetHtml(data, meta, templateId, reportTitle);
  } else if (messages && messages.length > 1) {
    bodyHtml = buildConversationBody(messages, meta, reportTitle);
  } else if (messages && messages.length === 1) {
    bodyHtml = buildMessageBody(messages[0].content, messages[0].role, meta, reportTitle);
  } else {
    bodyHtml = `<div class="content"><p>No content to display.</p></div>`;
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${esc(reportTitle)}</title>
  <style>
${PRINT_CSS}
  </style>
</head>
<body>
${coverHtml}
${bodyHtml}
</body>
</html>`;
}
