/**
 * Playwright-based app testing runner.
 *
 * Accepts a structured list of test steps (generated by AI), runs them against
 * a loaded HTML document in headless Chromium, and returns pass/fail results.
 *
 * Graceful degradation: if Playwright or Chromium is unavailable, returns a
 * single "skipped" result instead of crashing.
 */

import { logger } from "../logger";

export type TestStep = {
  name: string;
  action:
    | "waitForSelector"
    | "click"
    | "fill"
    | "expectText"
    | "expectVisible"
    | "expectNotVisible"
    | "expectTitle"
    | "expectCount";
  selector?: string;
  value?: string;
  timeout?: number;
};

export type TestPlan = {
  steps: TestStep[];
};

export type TestResult = {
  name: string;
  passed: boolean;
  message: string;
  screenshotBase64?: string | null;
  durationMs: number;
};

/**
 * Run a structured test plan against a given HTML document.
 * Uses Playwright's setContent() to load the HTML directly — avoids network
 * issues with the preview route and works entirely server-side.
 */
export async function runTestPlan(
  htmlContent: string,
  testPlan: TestPlan,
  options: { timeoutMs?: number } = {},
): Promise<TestResult[]> {
  const stepTimeout = options.timeoutMs ?? 5000;

  let chromium: typeof import("playwright").chromium;
  try {
    const playwright = await import("playwright");
    chromium = playwright.chromium;
  } catch (err) {
    logger.warn({ err }, "Playwright not available — skipping browser tests");
    return [
      {
        name: "Browser test environment",
        passed: false,
        message: "Playwright is not installed. Run `playwright install chromium` to enable tests.",
        screenshotBase64: null,
        durationMs: 0,
      },
    ];
  }

  // eslint-disable-next-line no-useless-assignment
  let browser: import("playwright").Browser | null = null;

  // Resolve system Chromium executable path.
  // Prefers PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH env var, then `which chromium`, then known paths.
  async function resolveChromiumPath(): Promise<string | undefined> {
    if (process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH) {
      return process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH;
    }
    const { execFile } = await import("node:child_process");
    const { existsSync } = await import("node:fs");
    // Try `which chromium` first
    await new Promise<void>((resolve) => {
      execFile("which", ["chromium"], { timeout: 2000 }, (err, stdout) => {
        if (!err && stdout.trim()) {
          process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH = stdout.trim();
        }
        resolve();
      });
    });
    if (process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH) {
      return process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH;
    }
    // Fall back to known system paths
    const candidates = [
      "/nix/var/nix/profiles/default/bin/chromium",
      "/run/current-system/sw/bin/chromium",
      "/usr/bin/chromium",
      "/usr/bin/chromium-browser",
      "/usr/bin/google-chrome",
    ];
    for (const p of candidates) {
      if (existsSync(p)) return p;
    }
    return undefined;
  }

  try {
    const executablePath = await resolveChromiumPath();
    browser = await chromium.launch({
      headless: true,
      ...(executablePath ? { executablePath } : {}),
      args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
    });
  } catch (err) {
    logger.warn({ err }, "Chromium launch failed — skipping browser tests");
    return [
      {
        name: "Browser launch",
        passed: false,
        message:
          "Could not launch Chromium. Install it with `nix-env -iA nixpkgs.chromium` or set PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH.",
        screenshotBase64: null,
        durationMs: 0,
      },
    ];
  }

  const results: TestResult[] = [];

  try {
    const context = await browser.newContext();
    const page = await context.newPage();

    // Load the HTML via setContent — avoids needing a live server
    await page.setContent(htmlContent, { waitUntil: "domcontentloaded", timeout: 10000 });

    for (const step of testPlan.steps) {
      const start = Date.now();
      let passed = false;
      let message = "";
      let screenshotBase64: string | null = null;

      try {
        const t = step.timeout ?? stepTimeout;

        switch (step.action) {
          case "waitForSelector": {
            if (!step.selector) throw new Error("waitForSelector requires selector");
            await page.waitForSelector(step.selector, { timeout: t });
            passed = true;
            message = `Element "${step.selector}" is present.`;
            break;
          }

          case "click": {
            if (!step.selector) throw new Error("click requires selector");
            await page.waitForSelector(step.selector, { timeout: t });
            await page.click(step.selector);
            passed = true;
            message = `Clicked "${step.selector}" successfully.`;
            break;
          }

          case "fill": {
            if (!step.selector) throw new Error("fill requires selector");
            if (step.value === undefined) throw new Error("fill requires value");
            await page.waitForSelector(step.selector, { timeout: t });
            await page.fill(step.selector, step.value);
            passed = true;
            message = `Filled "${step.selector}" with value.`;
            break;
          }

          case "expectText": {
            if (!step.selector) throw new Error("expectText requires selector");
            if (!step.value) throw new Error("expectText requires value");
            const el = await page.waitForSelector(step.selector, { timeout: t });
            const text = await el.textContent();
            const norm = (text ?? "").trim().toLowerCase();
            const expected = step.value.toLowerCase();
            if (norm.includes(expected)) {
              passed = true;
              message = `Text "${step.value}" found in "${step.selector}".`;
            } else {
              passed = false;
              message = `Expected text "${step.value}" but got "${(text ?? "").trim().slice(0, 80)}".`;
            }
            break;
          }

          case "expectVisible": {
            if (!step.selector) throw new Error("expectVisible requires selector");
            const visible = await page.isVisible(step.selector);
            if (visible) {
              passed = true;
              message = `"${step.selector}" is visible.`;
            } else {
              passed = false;
              message = `"${step.selector}" is not visible.`;
            }
            break;
          }

          case "expectNotVisible": {
            if (!step.selector) throw new Error("expectNotVisible requires selector");
            const notVisible = !(await page.isVisible(step.selector));
            if (notVisible) {
              passed = true;
              message = `"${step.selector}" is correctly hidden.`;
            } else {
              passed = false;
              message = `"${step.selector}" should be hidden but is visible.`;
            }
            break;
          }

          case "expectTitle": {
            const title = await page.title();
            if (step.value) {
              const titleMatch = title.toLowerCase().includes(step.value.toLowerCase());
              passed = titleMatch;
              message = titleMatch
                ? `Page title contains "${step.value}".`
                : `Page title "${title}" does not contain "${step.value}".`;
            } else {
              passed = title.length > 0;
              message = passed ? `Page has title: "${title}".` : "Page has no title.";
            }
            break;
          }

          case "expectCount": {
            if (!step.selector) throw new Error("expectCount requires selector");
            const count = await page.locator(step.selector).count();
            const expected = parseInt(step.value ?? "1", 10);
            passed = count >= expected;
            message = passed
              ? `Found ${count} element(s) matching "${step.selector}".`
              : `Expected ≥${expected} element(s) matching "${step.selector}" but found ${count}.`;
            break;
          }

          default: {
            passed = false;
            message = `Unknown action: ${String((step as { action: unknown }).action)}`;
          }
        }
      } catch (err) {
        passed = false;
        message = err instanceof Error ? err.message : "Test step threw an unexpected error.";

        // Capture screenshot on failure
        try {
          const buf = await page.screenshot({ type: "png", fullPage: false });
          screenshotBase64 = buf.toString("base64");
        } catch {
          // Non-fatal — screenshot capture can fail
        }
      }

      results.push({
        name: step.name,
        passed,
        message,
        screenshotBase64: passed ? null : screenshotBase64,
        durationMs: Date.now() - start,
      });
    }

    await context.close();
  } finally {
    await browser.close().catch(() => {});
  }

  return results;
}
