import React from "react";
import { Modal, Pressable, ScrollView, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { useColors } from "@/hooks/useColors";

export const LEGAL_SECTIONS = [
  {
    heading: "How Ora works",
    body: "Ora is an AI assistant. Responses are generated by AI models and may not always be accurate.",
  },
  {
    heading: "What we collect",
    body: "Account identifiers, conversation messages, uploaded file content (processed temporarily and not retained beyond the session), and usage counts. Voice audio is processed in real time and is not stored.",
  },
  {
    heading: "Memory",
    body: "Ora can save notes about you to improve future replies. You control this. All saved memories can be viewed and deleted from Settings at any time.",
  },
  {
    heading: "Third-party AI",
    body: "Responses are generated via third-party AI providers. Content you send may be processed by those providers subject to their own terms.",
  },
  {
    heading: "Not professional advice",
    body: "Ora is not a licensed medical, legal, financial, or safety professional. Do not rely on Ora for decisions in those areas.",
  },
  {
    heading: "Acceptable use",
    body: "Ora may not be used for illegal activity, harassment, generating harmful content, or attempting to bypass its safety guidelines.",
  },
  {
    heading: "Contact",
    body: "For questions or to request data deletion, contact us at support on mustaflow.com.",
  },
] as const;

interface LegalPrivacyModalProps {
  visible: boolean;
  onClose: () => void;
}

export function LegalPrivacyModal({ visible, onClose }: LegalPrivacyModalProps) {
  const c = useColors();
  const insets = useSafeAreaInsets();

  return (
    <Modal
      visible={visible}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={onClose}
    >
      <View style={{ flex: 1, backgroundColor: c.background }}>
        <View
          style={{
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            paddingHorizontal: 20,
            paddingTop: insets.top + 16,
            paddingBottom: 12,
            borderBottomWidth: 1,
            borderBottomColor: c.border,
          }}
        >
          <Text
            style={{
              color: c.foreground,
              fontFamily: "Inter_700Bold",
              fontSize: 17,
            }}
          >
            Legal &amp; Privacy
          </Text>
          <Pressable
            onPress={onClose}
            hitSlop={12}
            style={({ pressed }) => ({ opacity: pressed ? 0.6 : 1 })}
          >
            <Text
              style={{
                color: c.accentForeground,
                fontFamily: "Inter_600SemiBold",
                fontSize: 15,
              }}
            >
              Done
            </Text>
          </Pressable>
        </View>

        <ScrollView
          contentContainerStyle={{
            padding: 20,
            paddingBottom: insets.bottom + 24,
            gap: 16,
          }}
        >
          {LEGAL_SECTIONS.map(({ heading, body }) => (
            <View key={heading} style={{ gap: 4 }}>
              <Text
                style={{
                  color: c.foreground,
                  fontFamily: "Inter_600SemiBold",
                  fontSize: 13,
                }}
              >
                {heading}
              </Text>
              <Text style={{ color: c.mutedForeground, fontSize: 13, lineHeight: 20 }}>
                {body}
              </Text>
            </View>
          ))}
        </ScrollView>
      </View>
    </Modal>
  );
}
