/**
 * Health endpoint injection for generated apps.
 *
 * When the builder creates or refines a server-stack project, it must include
 * a health endpoint in the generated files BEFORE the Test Candidate snapshot
 * is created. This ensures:
 *   1. The tested snapshot and the production deployment contain identical files.
 *   2. The platform health probe can verify the app is alive without mutating source.
 *
 * For React/Vite (static) projects, no injection is needed — the health probe
 * uses HTTP GET on healthCheckPath (default "/"), which always returns 200
 * for a running static file server.
 *
 * For unknown or custom stacks, no injection is done — the platform falls back
 * to probing "/" and treating any HTTP response as healthy.
 */

// Use the canonical BuilderFile type from builder.ts so callers share the same nominal type.
import type { BuilderFile } from "./builder";

const NODE_HEALTHZ_CONTENT = `// Auto-generated by NabuFlow — do not edit.
// Registers GET /healthz → { ok: true } for container health probes.
import { Router } from "express";
const router = Router();
router.get("/healthz", (_req, res) => {
  res.json({ ok: true, ts: Date.now() });
});
export default router;
`;

const NEXTJS_HEALTHZ_CONTENT = `// Auto-generated by NabuFlow — do not edit.
// Next.js App Router API route: GET /api/healthz → { ok: true }
import { NextResponse } from "next/server";
export function GET() {
  return NextResponse.json({ ok: true, ts: Date.now() });
}
`;

const FLASK_HEALTHZ_CONTENT = `# Auto-generated by NabuFlow — do not edit.
# Register this blueprint in your app factory: app.register_blueprint(healthz_bp)
from flask import Blueprint, jsonify
import time

healthz_bp = Blueprint("healthz", __name__)

@healthz_bp.route("/healthz")
def healthz():
    return jsonify({"ok": True, "ts": int(time.time() * 1000)})
`;

const FASTAPI_HEALTHZ_CONTENT = `# Auto-generated by NabuFlow — do not edit.
# Include this router in main.py: app.include_router(healthz_router)
from fastapi import APIRouter
import time

healthz_router = APIRouter()

@healthz_router.get("/healthz")
def healthz():
    return {"ok": True, "ts": int(time.time() * 1000)}
`;

interface HealthConfig {
  /** File path for the injected health endpoint module. */
  path: string;
  content: string;
  mimeType: string;
  /** Health probe path the platform will poll. */
  healthCheckPath: string;
}

const HEALTH_BY_STACK: Record<string, HealthConfig> = {
  "node-api": {
    path: "src/routes/_platform_healthz.ts",
    content: NODE_HEALTHZ_CONTENT,
    mimeType: "text/typescript",
    healthCheckPath: "/healthz",
  },
  node: {
    path: "src/routes/_platform_healthz.ts",
    content: NODE_HEALTHZ_CONTENT,
    mimeType: "text/typescript",
    healthCheckPath: "/healthz",
  },
  nextjs: {
    path: "src/app/api/healthz/route.ts",
    content: NEXTJS_HEALTHZ_CONTENT,
    mimeType: "text/typescript",
    healthCheckPath: "/api/healthz",
  },
  "python-flask": {
    path: "_platform_healthz.py",
    content: FLASK_HEALTHZ_CONTENT,
    mimeType: "text/x-python",
    healthCheckPath: "/healthz",
  },
  "python-fastapi": {
    path: "_platform_healthz.py",
    content: FASTAPI_HEALTHZ_CONTENT,
    mimeType: "text/x-python",
    healthCheckPath: "/healthz",
  },
};

/**
 * Inject a platform health endpoint file into a set of generated files,
 * if not already present for the given stack.
 *
 * Returns the (potentially augmented) file array. Original array not mutated.
 *
 * Skips injection for:
 *   - react-vite (static serving; health probe uses "/" response)
 *   - unknown / unrecognised stacks
 *   - any stack that already has a health endpoint at the expected path
 */
export function injectHealthEndpoint(
  files: BuilderFile[],
  stack: string | null | undefined,
): BuilderFile[] {
  if (!stack) return files;

  const config = HEALTH_BY_STACK[stack];
  if (!config) return files;

  // Skip if the project already defines a health endpoint at the expected path.
  if (files.some((f) => f.path === config.path)) return files;

  return [...files, { path: config.path, content: config.content, mimeType: config.mimeType }];
}

/**
 * Return the platform health check path for a given stack.
 * Falls back to "/" for static/unknown stacks.
 */
export function healthCheckPathForStack(stack: string | null | undefined): string {
  if (!stack) return "/";
  return HEALTH_BY_STACK[stack]?.healthCheckPath ?? "/";
}

/**
 * Poll a URL+path until it returns any HTTP response (any status code),
 * or until the timeout is reached.
 *
 * "Any response" is the definition of healthy: ECONNREFUSED = not healthy,
 * HTTP 404 = healthy (the app is responding, just no route there).
 *
 * @param baseUrl  Container URL without trailing slash.
 * @param path     Path to probe (e.g. "/healthz" or "/").
 * @param timeoutMs  Total time to wait in milliseconds (default: 60_000).
 */
export async function waitForContainerHealthy(
  baseUrl: string,
  path: string,
  timeoutMs = 60_000,
): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  const url = baseUrl.replace(/\/$/, "") + path;

  while (Date.now() < deadline) {
    try {
      const r = await fetch(url, {
        method: "GET",
        signal: AbortSignal.timeout(5_000),
      });
      // Any HTTP response (including 4xx/5xx) means the process is alive.
      if (r.status > 0) return true;
    } catch {
      // ECONNREFUSED, AbortError, etc. — container not ready yet.
    }
    await new Promise<void>((resolve) => setTimeout(resolve, 3_000));
  }

  return false;
}
