import { describe, expect, it } from "vitest";
import { getTableColumns, type SQL } from "drizzle-orm";
import { PgDialect } from "drizzle-orm/pg-core";
import { chatMessagesTable, type InsertChatMessage } from "../../../../lib/db/src/schema/messages";

describe("chat message search schema", () => {
  it("owns the historical generated search column in the canonical schema", () => {
    const column = getTableColumns(chatMessagesTable).contentTsv;
    const generated = column.generated;

    expect(column.getSQLType()).toBe("tsvector");
    expect(generated?.type).toBe("always");
    expect(generated?.mode).toBe("stored");
    expect(new PgDialect().sqlToQuery(generated?.as as SQL).sql).toBe(
      "to_tsvector('english', coalesce(content, ''))",
    );
  });

  it("keeps the database-generated column out of message inserts", () => {
    const insert: InsertChatMessage = {
      projectId: 1,
      role: "user",
      content: "hello",
      // @ts-expect-error content_tsv is generated by PostgreSQL, never supplied by callers.
      contentTsv: "hello",
    };

    void insert;
  });
});
