import {
  CAPABILITY_INTENT_URL,
  DATABASE_BATCH_MAX_STATEMENTS,
  DATABASE_CAPABILITY_ACTION,
  DATABASE_CAPABILITY_ERROR_MAP,
  DATABASE_CAPABILITY_NAME,
  DATABASE_CAPABILITY_PROVIDER,
  DATABASE_OPERATION_DEFAULT_TIMEOUT_MS,
  DATABASE_OPERATION_MAX_TIMEOUT_MS,
  DATABASE_PARAMETER_MAX_COUNT,
  DATABASE_RESULT_MAX_BYTES,
  DATABASE_RESULT_MAX_ROWS,
  DATABASE_SQL_MAX_CHARS,
  RUNTIME_DATABASE_ERROR_CODES,
  RUNTIME_STRIPE_ERROR_CODES,
  STRIPE_CAPABILITY_ACTION,
  STRIPE_CAPABILITY_ERROR_MAP,
  STRIPE_CAPABILITY_NAME,
  STRIPE_CAPABILITY_PROVIDER,
  TENANT_DATABASE_URL_ENV,
  TENANT_RUNTIME_MODE_ENV,
  TENANT_RUNTIME_MODES,
} from "@workspace/tenant-runtime-contracts";

export const VENDORED_RUNTIME_SDK_VERSION = "nabu-runtime-sdk/v1" as const;
export const VENDORED_FLY_POSTGRES_VERSION = "8.20.0" as const;
export const VENDORED_FLY_POSTGRES_TYPES_VERSION = "8.20.0" as const;

export interface VendoredRuntimeSdkFile {
  path: string;
  content: string;
}

function canonicalSource(source: string): string {
  return `${source.replace(/\r\n?/gu, "\n").trim()}\n`;
}

const DATABASE_SOURCE = canonicalSource(String.raw`
// Generated by NabuFlow. This source-owned module is safe to inspect and edit.
// Cloudflare capability mode carries no credential or caller authority.

export const NABUFLOW_RUNTIME_SDK_VERSION = ${JSON.stringify(VENDORED_RUNTIME_SDK_VERSION)};

const MODE_ENV = ${JSON.stringify(TENANT_RUNTIME_MODE_ENV)};
const DATABASE_URL_ENV = ${JSON.stringify(TENANT_DATABASE_URL_ENV)};
const DIRECT_MODE = ${JSON.stringify(TENANT_RUNTIME_MODES[0])};
const CAPABILITY_MODE = ${JSON.stringify(TENANT_RUNTIME_MODES[1])};
const CAPABILITY_URL = ${JSON.stringify(CAPABILITY_INTENT_URL)};
const CAPABILITY_PROVIDER = ${JSON.stringify(DATABASE_CAPABILITY_PROVIDER)};
const CAPABILITY_NAME = ${JSON.stringify(DATABASE_CAPABILITY_NAME)};
const CAPABILITY_ACTION = ${JSON.stringify(DATABASE_CAPABILITY_ACTION)};
const MAX_SQL_CHARS = ${DATABASE_SQL_MAX_CHARS};
const MAX_PARAMETERS = ${DATABASE_PARAMETER_MAX_COUNT};
const MAX_BATCH_STATEMENTS = ${DATABASE_BATCH_MAX_STATEMENTS};
const MAX_ROWS = ${DATABASE_RESULT_MAX_ROWS};
const MAX_RESPONSE_BYTES = ${DATABASE_RESULT_MAX_BYTES};
const DEFAULT_TIMEOUT_MS = ${DATABASE_OPERATION_DEFAULT_TIMEOUT_MS};
const MAX_TIMEOUT_MS = ${DATABASE_OPERATION_MAX_TIMEOUT_MS};
const ERROR_CODES = Object.freeze(${JSON.stringify(RUNTIME_DATABASE_ERROR_CODES)} as const);
const PROVIDER_ERROR_MAP = Object.freeze(
  ${JSON.stringify(DATABASE_CAPABILITY_ERROR_MAP)} as const,
) as Readonly<Record<string, (typeof ERROR_CODES)[number]>>;

export type NabuFlowRuntimeMode = typeof DIRECT_MODE | typeof CAPABILITY_MODE;
export type DatabaseParameter = string | number | boolean | null;

export interface DatabaseStatement {
  sql: string;
  params: DatabaseParameter[];
}

export interface DatabaseStatementResult<Row extends Record<string, unknown> = Record<string, unknown>> {
  command: string;
  rowCount: number;
  rows: Row[];
}

export interface DatabaseOperationOptions {
  signal?: AbortSignal;
  timeoutMs?: number;
}

export type NabuFlowDatabaseErrorCode = (typeof ERROR_CODES)[number];

export class NabuFlowDatabaseError extends Error {
  readonly name = "NabuFlowDatabaseError";

  constructor(
    readonly code: NabuFlowDatabaseErrorCode,
    readonly retryable: boolean,
  ) {
    super(errorMessage(code));
  }
}

export class NabuFlowDirectDriverError extends NabuFlowDatabaseError {}

export interface DirectDatabaseDriver {
  query(
    sql: string,
    params: DatabaseParameter[],
    options: { signal: AbortSignal },
  ): Promise<DatabaseStatementResult>;
  atomicBatch(
    statements: DatabaseStatement[],
    options: { signal: AbortSignal },
  ): Promise<DatabaseStatementResult[]>;
}

export type DirectDatabaseDriverFactory = (
  databaseUrl: string,
) => DirectDatabaseDriver | Promise<DirectDatabaseDriver>;

export interface NabuFlowDatabaseClient {
  readonly mode: NabuFlowRuntimeMode;
  query<Row extends Record<string, unknown> = Record<string, unknown>>(
    sql: string,
    params?: DatabaseParameter[],
    options?: DatabaseOperationOptions,
  ): Promise<DatabaseStatementResult<Row>>;
  batch(
    statements: DatabaseStatement[],
    options?: DatabaseOperationOptions,
  ): Promise<DatabaseStatementResult[]>;
}

export interface CreateNabuFlowDatabaseOptions {
  directDriverFactory?: DirectDatabaseDriverFactory;
  fetch?: typeof globalThis.fetch;
}

export type DrizzleProxyMethod = "all" | "execute" | "get" | "run" | "values";
export type DrizzleProxyExecutor = (
  sql: string,
  params: DatabaseParameter[],
  method: DrizzleProxyMethod,
) => Promise<{ rows: unknown[] }>;

function errorMessage(code: NabuFlowDatabaseErrorCode): string {
  switch (code) {
    case "configuration":
      return "The database runtime is not configured";
    case "invalid_query":
      return "The database request is invalid";
    case "conflict":
      return "The database request conflicts with existing data";
    case "timeout":
      return "The database request timed out";
    case "cancelled":
      return "The database request was cancelled";
    case "unavailable":
      return "The database is temporarily unavailable";
    case "policy_rejected":
      return "The database request was rejected by policy";
    case "internal":
      return "The database request could not be completed";
  }
}

function fail(code: NabuFlowDatabaseErrorCode, retryable = false): never {
  throw new NabuFlowDatabaseError(code, retryable);
}

function readEnvironment(name: string): string | undefined {
  const runtimeGlobal = globalThis as typeof globalThis & {
    process?: { env?: Record<string, string | undefined> };
  };
  return runtimeGlobal.process?.env?.[name];
}

function readMode(): NabuFlowRuntimeMode {
  const value = readEnvironment(MODE_ENV);
  if (value === DIRECT_MODE || value === CAPABILITY_MODE) return value;
  return fail("configuration");
}

// Static imports resolve the explicit platform mode before application code
// runs. The resolved value is never read from request input or revisited.
const RESOLVED_RUNTIME_MODE = readMode();

function validParameter(value: unknown): value is DatabaseParameter {
  return (
    value === null ||
    typeof value === "string" ||
    typeof value === "boolean" ||
    (typeof value === "number" && Number.isFinite(value))
  );
}

function validateStatement(sql: string, params: DatabaseParameter[]): DatabaseStatement {
  if (
    typeof sql !== "string" ||
    sql.length === 0 ||
    sql.length > MAX_SQL_CHARS ||
    sql.includes("\0") ||
    !Array.isArray(params) ||
    params.length > MAX_PARAMETERS ||
    !params.every(validParameter)
  ) {
    return fail("invalid_query");
  }
  return { sql, params: params.slice() };
}

function validateTimeout(value: number | undefined): number {
  const timeout = value ?? DEFAULT_TIMEOUT_MS;
  if (!Number.isInteger(timeout) || timeout < 1 || timeout > MAX_TIMEOUT_MS) {
    return fail("policy_rejected");
  }
  return timeout;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function normalizeResult(value: unknown): DatabaseStatementResult {
  if (!isRecord(value)) return fail("internal");
  const command = value.command;
  const rowCount = value.rowCount;
  const rows = value.rows;
  if (
    typeof command !== "string" ||
    command.length === 0 ||
    command.length > 40 ||
    !Number.isInteger(rowCount) ||
    Number(rowCount) < 0 ||
    !Array.isArray(rows) ||
    rows.length > MAX_ROWS ||
    !rows.every(isRecord)
  ) {
    return fail("internal");
  }
  const result = {
    command,
    rowCount: Number(rowCount),
    rows: rows.map((row) => ({ ...row })),
  };
  let serialized: string;
  try {
    serialized = JSON.stringify(result);
  } catch {
    return fail("internal");
  }
  if (serialized.length > MAX_RESPONSE_BYTES) return fail("policy_rejected");
  return result;
}

function providerErrorCode(providerCode: string, status: number): NabuFlowDatabaseErrorCode {
  const mapped = PROVIDER_ERROR_MAP[providerCode] as NabuFlowDatabaseErrorCode | undefined;
  if (mapped !== undefined) return mapped;
  if (status === 408 || status === 504) return "timeout";
  if (status === 409) return "conflict";
  if (status === 413 || status === 422) return "policy_rejected";
  if (status === 429 || status === 502 || status === 503) return "unavailable";
  return "internal";
}

async function withDeadline<T>(
  options: DatabaseOperationOptions | undefined,
  operation: (signal: AbortSignal) => Promise<T>,
): Promise<T> {
  const timeoutMs = validateTimeout(options?.timeoutMs);
  const controller = new AbortController();
  let timedOut = false;
  let cancelled = options?.signal?.aborted === true;
  const cancel = () => {
    cancelled = true;
    controller.abort();
  };
  if (cancelled) return fail("cancelled");
  options?.signal?.addEventListener("abort", cancel, { once: true });
  const timer = setTimeout(() => {
    timedOut = true;
    controller.abort();
  }, timeoutMs);
  try {
    return await operation(controller.signal);
  } catch (error) {
    if (timedOut) return fail("timeout", true);
    if (cancelled) return fail("cancelled");
    if (error instanceof NabuFlowDatabaseError) throw error;
    return fail("internal");
  } finally {
    clearTimeout(timer);
    options?.signal?.removeEventListener("abort", cancel);
  }
}

function requestId(): string {
  return "sdk-db-" + crypto.randomUUID();
}

function operationIntent(operation: unknown, id: string): string {
  return JSON.stringify({
    v: 1,
    capability: { provider: CAPABILITY_PROVIDER, name: CAPABILITY_NAME },
    action: CAPABILITY_ACTION,
    requestId: id,
    input: operation,
  });
}

function parseErrorResponse(value: unknown, status: number): NabuFlowDatabaseError {
  if (
    !isRecord(value) ||
    value.ok !== false ||
    typeof value.code !== "string" ||
    typeof value.retryable !== "boolean"
  ) {
    return new NabuFlowDatabaseError("internal", false);
  }
  return new NabuFlowDatabaseError(
    providerErrorCode(value.code, status),
    value.retryable,
  );
}

function parseCapabilityResponse(
  value: unknown,
  expectedRequestId: string,
  expectedKind: "statement" | "atomic-batch",
): DatabaseStatementResult | DatabaseStatementResult[] {
  if (
    !isRecord(value) ||
    value.ok !== true ||
    value.actedBy !== "database-broker" ||
    value.requestId !== expectedRequestId ||
    !isRecord(value.capability) ||
    value.capability.provider !== CAPABILITY_PROVIDER ||
    value.capability.name !== CAPABILITY_NAME ||
    !isRecord(value.result) ||
    value.result.kind !== expectedKind
  ) {
    return fail("internal");
  }
  if (expectedKind === "statement") {
    return normalizeResult(value.result.result);
  }
  if (!Array.isArray(value.result.results) || value.result.results.length > MAX_BATCH_STATEMENTS) {
    return fail("internal");
  }
  return value.result.results.map(normalizeResult);
}

export function createNabuFlowDatabase(
  options: CreateNabuFlowDatabaseOptions = {},
): NabuFlowDatabaseClient {
  // Mode is read exactly once. A call cannot override it and later environment
  // mutation cannot cause a direct/capability fallback.
  const mode = RESOLVED_RUNTIME_MODE;
  const fetchImpl = options.fetch ?? globalThis.fetch;
  let directDriver: Promise<DirectDatabaseDriver> | undefined;

  async function getDirectDriver(): Promise<DirectDatabaseDriver> {
    if (mode !== DIRECT_MODE) return fail("internal");
    if (directDriver !== undefined) return directDriver;
    const databaseUrl = readEnvironment(DATABASE_URL_ENV);
    if (typeof databaseUrl !== "string" || databaseUrl.length === 0) {
      return fail("configuration");
    }
    if (options.directDriverFactory === undefined) return fail("configuration");
    directDriver = Promise.resolve(options.directDriverFactory(databaseUrl)).catch(() =>
      fail("internal"),
    );
    return directDriver;
  }

  async function invokeCapability(
    operation: unknown,
    kind: "statement" | "atomic-batch",
    callOptions: DatabaseOperationOptions | undefined,
  ): Promise<DatabaseStatementResult | DatabaseStatementResult[]> {
    if (typeof fetchImpl !== "function") return fail("configuration");
    return withDeadline(callOptions, async (signal) => {
      const id = requestId();
      let response: Response;
      try {
        response = await fetchImpl(CAPABILITY_URL, {
          method: "POST",
          headers: {
            accept: "application/json",
            "content-type": "application/json; charset=utf-8",
          },
          body: operationIntent(operation, id),
          signal,
        });
      } catch (error) {
        if (signal.aborted) throw error;
        return fail("unavailable", true);
      }
      let body: unknown;
      try {
        const text = await response.text();
        if (text.length > MAX_RESPONSE_BYTES) return fail("policy_rejected");
        body = JSON.parse(text) as unknown;
      } catch {
        return fail("internal");
      }
      if (!response.ok) throw parseErrorResponse(body, response.status);
      return parseCapabilityResponse(body, id, kind);
    });
  }

  const client: NabuFlowDatabaseClient = {
    mode,
    async query<Row extends Record<string, unknown> = Record<string, unknown>>(
      sql: string,
      params: DatabaseParameter[] = [],
      callOptions?: DatabaseOperationOptions,
    ): Promise<DatabaseStatementResult<Row>> {
      const statement = validateStatement(sql, params);
      const result =
        mode === DIRECT_MODE
          ? await withDeadline(callOptions, async (signal) =>
              normalizeResult(await (await getDirectDriver()).query(statement.sql, statement.params, { signal })),
            )
          : await invokeCapability({ ...statement, kind: "statement" }, "statement", callOptions);
      if (Array.isArray(result)) return fail("internal");
      return result as DatabaseStatementResult<Row>;
    },
    async batch(
      statements: DatabaseStatement[],
      callOptions?: DatabaseOperationOptions,
    ): Promise<DatabaseStatementResult[]> {
      if (
        !Array.isArray(statements) ||
        statements.length === 0 ||
        statements.length > MAX_BATCH_STATEMENTS
      ) {
        return fail("invalid_query");
      }
      const validated = statements.map((statement) =>
        validateStatement(statement.sql, statement.params),
      );
      const result =
        mode === DIRECT_MODE
          ? await withDeadline(callOptions, async (signal) =>
              (await (await getDirectDriver()).atomicBatch(validated, { signal })).map(normalizeResult),
            )
          : await invokeCapability(
              { kind: "atomic-batch", statements: validated },
              "atomic-batch",
              callOptions,
            );
      if (!Array.isArray(result)) return fail("internal");
      return result;
    },
  };
  return Object.freeze(client);
}

export function createDrizzleProxyAdapter(client: NabuFlowDatabaseClient): DrizzleProxyExecutor {
  return async (sql, params, method) => {
    const result = await client.query(sql, params);
    if (method === "values") {
      return { rows: result.rows.map((row) => Object.values(row)) };
    }
    if (method === "get") {
      return { rows: result.rows.length === 0 ? [] : [result.rows[0]] };
    }
    return { rows: result.rows };
  };
}
`);

const FLY_POSTGRES_SOURCE = canonicalSource(String.raw`
// Generated by NabuFlow. This platform-owned direct adapter is lazy: Cloudflare
// capability mode never imports pg and never reads a database credential.

import type { PoolClient, QueryResult } from "pg";
import {
  NabuFlowDirectDriverError,
  createNabuFlowDatabase as createDatabaseClient,
  type CreateNabuFlowDatabaseOptions,
  type DatabaseParameter,
  type DatabaseStatement,
  type DatabaseStatementResult,
  type DirectDatabaseDriver,
  type DirectDatabaseDriverFactory,
  type NabuFlowDatabaseClient,
  type NabuFlowDatabaseErrorCode,
} from "./db.js";

type PgPool = {
  connect(): Promise<PoolClient>;
};

type PgModule = {
  Pool: new (options: {
    connectionString: string;
    max: number;
    idleTimeoutMillis: number;
    connectionTimeoutMillis: number;
  }) => PgPool;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function classifyPostgresError(error: unknown): NabuFlowDirectDriverError {
  if (error instanceof NabuFlowDirectDriverError) return error;
  const code = isRecord(error) && typeof error.code === "string" ? error.code : "";
  let mapped: NabuFlowDatabaseErrorCode = "internal";
  let retryable = false;
  if (/^23/u.test(code)) mapped = "conflict";
  else if (/^(?:22|42)/u.test(code)) mapped = "invalid_query";
  else if (/^(?:08|53|57P0)/u.test(code)) {
    mapped = "unavailable";
    retryable = true;
  }
  return new NabuFlowDirectDriverError(mapped, retryable);
}

function normalizePgResult(result: QueryResult): DatabaseStatementResult {
  return {
    command: result.command,
    rowCount: result.rowCount ?? 0,
    rows: result.rows as Array<Record<string, unknown>>,
  };
}

async function withClient<T>(
  pool: PgPool,
  signal: AbortSignal,
  operation: (client: PoolClient, destroy: () => void) => Promise<T>,
): Promise<T> {
  if (signal.aborted) throw new NabuFlowDirectDriverError("cancelled", false);
  let client: PoolClient;
  try {
    client = await pool.connect();
  } catch (error) {
    throw classifyPostgresError(error);
  }
  let destroyed = false;
  const destroy = () => {
    if (destroyed) return;
    destroyed = true;
    client.release(true);
  };
  const abort = () => destroy();
  signal.addEventListener("abort", abort, { once: true });
  try {
    if (signal.aborted) throw new NabuFlowDirectDriverError("cancelled", false);
    return await operation(client, destroy);
  } catch (error) {
    if (signal.aborted) throw new NabuFlowDirectDriverError("cancelled", false);
    throw classifyPostgresError(error);
  } finally {
    signal.removeEventListener("abort", abort);
    if (!destroyed) client.release();
  }
}

export const createNabuFlowFlyPostgresDriverFactory: DirectDatabaseDriverFactory =
  async (databaseUrl) => {
    let pg: PgModule;
    try {
      pg = (await import("pg")) as PgModule;
    } catch {
      throw new NabuFlowDirectDriverError("configuration", false);
    }
    const pool = new pg.Pool({
      connectionString: databaseUrl,
      max: 4,
      idleTimeoutMillis: 10_000,
      connectionTimeoutMillis: 10_000,
    });
    const driver: DirectDatabaseDriver = {
      async query(sql, params, options) {
        return withClient(pool, options.signal, async (client) =>
          normalizePgResult(await client.query(sql, params)),
        );
      },
      async atomicBatch(statements: DatabaseStatement[], options) {
        return withClient(pool, options.signal, async (client, destroy) => {
          let began = false;
          try {
            await client.query("BEGIN");
            began = true;
            const results: DatabaseStatementResult[] = [];
            for (const statement of statements) {
              if (options.signal.aborted) {
                destroy();
                throw new NabuFlowDirectDriverError("cancelled", false);
              }
              results.push(normalizePgResult(await client.query(statement.sql, statement.params)));
            }
            await client.query("COMMIT");
            return results;
          } catch (error) {
            if (began && !options.signal.aborted) {
              try {
                await client.query("ROLLBACK");
              } catch {
                destroy();
              }
            }
            throw error;
          }
        });
      },
    };
    return Object.freeze(driver);
  };

/**
 * Generated applications keep calling createNabuFlowDatabase() with no
 * substrate-specific code. This wrapper injects the platform-owned Fly
 * adapter, while an explicitly supplied factory remains authoritative.
 */
export function createNabuFlowDatabase(
  options: CreateNabuFlowDatabaseOptions = {},
): NabuFlowDatabaseClient {
  return createDatabaseClient({
    ...options,
    directDriverFactory:
      options.directDriverFactory ?? createNabuFlowFlyPostgresDriverFactory,
  });
}
`);

const PAYMENTS_SOURCE = canonicalSource(String.raw`
// Generated by NabuFlow. Cloudflare capability mode carries no payment key or caller authority.

export const NABUFLOW_RUNTIME_SDK_VERSION = ${JSON.stringify(VENDORED_RUNTIME_SDK_VERSION)};

const MODE_ENV = ${JSON.stringify(TENANT_RUNTIME_MODE_ENV)};
const DIRECT_MODE = ${JSON.stringify(TENANT_RUNTIME_MODES[0])};
const CAPABILITY_MODE = ${JSON.stringify(TENANT_RUNTIME_MODES[1])};
const CAPABILITY_URL = ${JSON.stringify(CAPABILITY_INTENT_URL)};
const CAPABILITY_PROVIDER = ${JSON.stringify(STRIPE_CAPABILITY_PROVIDER)};
const CAPABILITY_NAME = ${JSON.stringify(STRIPE_CAPABILITY_NAME)};
const CAPABILITY_ACTION = ${JSON.stringify(STRIPE_CAPABILITY_ACTION)};
const ERROR_CODES = Object.freeze(${JSON.stringify(RUNTIME_STRIPE_ERROR_CODES)} as const);
const PROVIDER_ERROR_MAP = Object.freeze(
  ${JSON.stringify(STRIPE_CAPABILITY_ERROR_MAP)} as const,
) as Readonly<Record<string, (typeof ERROR_CODES)[number]>>;

export type NabuFlowPaymentsErrorCode = (typeof ERROR_CODES)[number];
export interface PaymentIntentResult {
  id: string;
  status: string;
  amount: number;
  amountReceived: number;
  currency: string;
  created: number;
  livemode: false;
}
export interface CreatePaymentIntentInput {
  idempotencyKey: string;
  amount: number;
  currency: string;
}
export interface DirectPaymentsDriver {
  createPaymentIntent(input: CreatePaymentIntentInput): Promise<PaymentIntentResult>;
  retrievePaymentIntent(paymentIntentId: string): Promise<PaymentIntentResult>;
}
export interface CreateNabuFlowPaymentsOptions {
  directDriver?: DirectPaymentsDriver;
  fetch?: typeof globalThis.fetch;
}
export interface NabuFlowPaymentsClient {
  readonly mode: typeof DIRECT_MODE | typeof CAPABILITY_MODE;
  createPaymentIntent(input: CreatePaymentIntentInput): Promise<PaymentIntentResult>;
  retrievePaymentIntent(paymentIntentId: string): Promise<PaymentIntentResult>;
}

export class NabuFlowPaymentsError extends Error {
  readonly name = "NabuFlowPaymentsError";
  constructor(readonly code: NabuFlowPaymentsErrorCode, readonly retryable: boolean) {
    super(message(code));
  }
}

function message(code: NabuFlowPaymentsErrorCode): string {
  switch (code) {
    case "configuration": return "The payments runtime is not configured";
    case "invalid_request": return "The payment request is invalid";
    case "conflict": return "The payment request conflicts with an earlier operation";
    case "timeout": return "The payment request timed out";
    case "cancelled": return "The payment request was cancelled";
    case "unavailable": return "Payments are temporarily unavailable";
    case "policy_rejected": return "The payment request was rejected by policy";
    case "internal": return "The payment request could not be completed";
  }
}
function fail(code: NabuFlowPaymentsErrorCode, retryable = false): never {
  throw new NabuFlowPaymentsError(code, retryable);
}
function readMode(): typeof DIRECT_MODE | typeof CAPABILITY_MODE {
  const runtimeGlobal = globalThis as typeof globalThis & {
    process?: { env?: Record<string, string | undefined> };
  };
  const value = runtimeGlobal.process?.env?.[MODE_ENV];
  if (value === DIRECT_MODE || value === CAPABILITY_MODE) return value;
  return fail("configuration");
}
const RESOLVED_RUNTIME_MODE = readMode();
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function validPaymentIntent(value: unknown): value is PaymentIntentResult {
  return isRecord(value) &&
    typeof value.id === "string" && /^pi_[A-Za-z0-9]+$/u.test(value.id) &&
    typeof value.status === "string" &&
    Number.isInteger(value.amount) && Number(value.amount) >= 0 &&
    Number.isInteger(value.amountReceived) && Number(value.amountReceived) >= 0 &&
    typeof value.currency === "string" && /^[a-z]{3}$/u.test(value.currency) &&
    Number.isInteger(value.created) && value.livemode === false;
}
function validateCreate(input: CreatePaymentIntentInput): CreatePaymentIntentInput {
  if (!isRecord(input) || typeof input.idempotencyKey !== "string" ||
      input.idempotencyKey.length < 16 || input.idempotencyKey.length > 200 ||
      !Number.isInteger(input.amount) || input.amount < 1 || input.amount > 99_999_999 ||
      typeof input.currency !== "string" || !/^[a-z]{3}$/u.test(input.currency)) {
    return fail("invalid_request");
  }
  return { idempotencyKey: input.idempotencyKey, amount: input.amount, currency: input.currency };
}
function providerError(providerCode: string, status: number, retryable: boolean): NabuFlowPaymentsError {
  const mapped = PROVIDER_ERROR_MAP[providerCode];
  if (mapped !== undefined) return new NabuFlowPaymentsError(mapped, retryable);
  if (status === 408 || status === 504) return new NabuFlowPaymentsError("timeout", true);
  if (status === 409) return new NabuFlowPaymentsError("conflict", retryable);
  if (status === 413 || status === 422) return new NabuFlowPaymentsError("policy_rejected", false);
  if (status === 429 || status === 502 || status === 503) return new NabuFlowPaymentsError("unavailable", true);
  return new NabuFlowPaymentsError("internal", false);
}
async function invoke(fetchImpl: typeof globalThis.fetch, input: unknown): Promise<PaymentIntentResult> {
  const requestId = "sdk-pay-" + crypto.randomUUID();
  let response: Response;
  try {
    response = await fetchImpl(CAPABILITY_URL, {
      method: "POST",
      headers: { accept: "application/json", "content-type": "application/json; charset=utf-8" },
      body: JSON.stringify({
        v: 1,
        capability: { provider: CAPABILITY_PROVIDER, name: CAPABILITY_NAME },
        action: CAPABILITY_ACTION,
        requestId,
        input,
      }),
    });
  } catch {
    return fail("unavailable", true);
  }
  let body: unknown;
  try { body = JSON.parse(await response.text()) as unknown; } catch { return fail("internal"); }
  if (!response.ok) {
    if (!isRecord(body) || typeof body.code !== "string" || typeof body.retryable !== "boolean") {
      return fail("internal");
    }
    throw providerError(body.code, response.status, body.retryable);
  }
  if (!isRecord(body) || body.ok !== true || body.actedBy !== "stripe-broker" ||
      body.requestId !== requestId || !validPaymentIntent(body.paymentIntent)) return fail("internal");
  return { ...body.paymentIntent };
}

export function createNabuFlowPayments(
  options: CreateNabuFlowPaymentsOptions = {},
): NabuFlowPaymentsClient {
  const mode = RESOLVED_RUNTIME_MODE;
  const fetchImpl = options.fetch ?? globalThis.fetch;
  return Object.freeze({
    mode,
    async createPaymentIntent(input: CreatePaymentIntentInput): Promise<PaymentIntentResult> {
      const operation = { kind: "create-payment-intent", ...validateCreate(input) };
      const result = mode === DIRECT_MODE
        ? await (options.directDriver ?? fail("configuration")).createPaymentIntent(input)
        : await invoke(fetchImpl, operation);
      if (!validPaymentIntent(result)) return fail("internal");
      return { ...result };
    },
    async retrievePaymentIntent(paymentIntentId: string): Promise<PaymentIntentResult> {
      if (!/^pi_[A-Za-z0-9]+$/u.test(paymentIntentId)) return fail("invalid_request");
      const result = mode === DIRECT_MODE
        ? await (options.directDriver ?? fail("configuration")).retrievePaymentIntent(paymentIntentId)
        : await invoke(fetchImpl, { kind: "retrieve-payment-intent", paymentIntentId });
      if (!validPaymentIntent(result)) return fail("internal");
      return { ...result };
    },
  });
}
`);

const INDEX_SOURCE = canonicalSource(String.raw`
export { NABUFLOW_RUNTIME_SDK_VERSION } from "./db.js";
export * from "./db.js";
export * from "./payments.js";
export * from "./fly-postgres.js";
export { createNabuFlowDatabase } from "./fly-postgres.js";
`);

const VENDORED_FILES: readonly VendoredRuntimeSdkFile[] = Object.freeze([
  Object.freeze({ path: "nabuflow/runtime/db.ts", content: DATABASE_SOURCE }),
  Object.freeze({ path: "nabuflow/runtime/fly-postgres.ts", content: FLY_POSTGRES_SOURCE }),
  Object.freeze({ path: "nabuflow/runtime/payments.ts", content: PAYMENTS_SOURCE }),
  Object.freeze({ path: "nabuflow/runtime/index.ts", content: INDEX_SOURCE }),
]);

export function getVendoredRuntimeSdkFiles(): readonly VendoredRuntimeSdkFile[] {
  return VENDORED_FILES;
}
