import { Router, type IRouter } from "express";
import { strToU8, zipSync } from "fflate";
import { eq } from "drizzle-orm";
import { db, projectsTable, projectFilesTable, secretsTable } from "@workspace/db";
import { requireProjectOwnership } from "../lib/auth";
import { isBinaryMime } from "../lib/binary-mime";

const router: IRouter = Router();

function generateReadme(
  project: {
    name: string;
    kind: string;
    description: string | null;
    createdAt: Date;
    projectFormat?: string | null;
  },
  files: { path: string }[],
): string {
  const isReactVite = project.projectFormat === "react-vite";
  const gettingStarted = isReactVite
    ? `## Getting Started

This is a React + Vite project. Install dependencies and run the dev server:

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:5173](http://localhost:5173) to view the app.

### Build for production

\`\`\`bash
npm run build
npm run preview
\`\`\`

The \`dist/\` folder contains the production-ready static files.`
    : `## Getting Started

This is a static web application. Open \`index.html\` in a browser,
or serve the folder with any static file server:

\`\`\`bash
npx serve .
# or
python3 -m http.server 8080
\`\`\``;

  const notes = isReactVite
    ? `## Notes

- Stack: React 18, Vite 5, TypeScript, Tailwind CSS v3.
- Run \`npm install\` first — CDN dependencies are not used.
- Secrets are not included in this export; add them to \`.env\` (see \`.env.example\`).`
    : `## Notes

- Generated files use Tailwind CSS and Lucide icons via CDN.
- No build step required for web; mobile targets may need Expo setup.
- Secrets are not included in this export for security reasons.`;

  return `# ${project.name}

> Generated by MustaFlow AI

## Project Info

- **Type**: ${project.kind}${isReactVite ? " (React + Vite)" : ""}
- **Description**: ${project.description ?? "No description provided"}
- **Created**: ${new Date(project.createdAt).toLocaleDateString()}

## Files

${files.map((f) => `- \`${f.path}\``).join("\n")}

${gettingStarted}

## Environment Variables

Copy \`.env.example\` to \`.env\` and fill in your values.
Never commit \`.env\` to version control.

${notes}
`;
}

function generateEnvExample(secretNames: string[]): string {
  const lines = [
    "# Environment Variables — MustaFlow AI Export",
    "# Copy this file to .env and fill in real values.",
    "# NEVER commit your real .env to version control.",
    "",
  ];
  if (secretNames.length > 0) {
    lines.push("# Project secrets (add your real values below):");
    for (const name of secretNames) {
      lines.push(`${name}=`);
    }
  } else {
    lines.push("# No secrets configured for this project.");
  }
  lines.push("");
  lines.push("# Add any additional environment variables your app needs:");
  lines.push("# MY_API_KEY=");
  return lines.join("\n");
}

router.get("/projects/:id/export", requireProjectOwnership, async (req, res): Promise<void> => {
  const projectId = Number(req.params.id);

  const [project] = await db.select().from(projectsTable).where(eq(projectsTable.id, projectId));
  if (!project) {
    res.status(404).json({ error: "Project not found" });
    return;
  }

  const files = await db
    .select()
    .from(projectFilesTable)
    .where(eq(projectFilesTable.projectId, projectId));

  const secrets = await db
    .select({ name: secretsTable.name })
    .from(secretsTable)
    .where(eq(secretsTable.projectId, projectId));

  const safeName = project.name.replace(/[^a-z0-9]/gi, "-").toLowerCase();

  // Build the zip in-memory using fflate (pure ESM, no CJS issues)
  const zipFiles: Record<string, Uint8Array> = {};

  for (const file of files) {
    const mime = file.mimeType ?? "";
    zipFiles[file.path] = isBinaryMime(mime)
      ? new Uint8Array(Buffer.from(file.content, "base64"))
      : strToU8(file.content);
  }
  zipFiles["README.md"] = strToU8(generateReadme(project, files));
  zipFiles[".env.example"] = strToU8(generateEnvExample(secrets.map((s) => s.name)));

  const zipped = zipSync(zipFiles, { level: 9 });

  res.setHeader("Content-Type", "application/zip");
  res.setHeader("Content-Disposition", `attachment; filename="${safeName}.zip"`);
  res.end(Buffer.from(zipped));
});

export default router;
