// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/workspace/BeginnerWorkspace.tsx": () => import("../components/mockups/workspace/BeginnerWorkspace.tsx"),
  "./components/mockups/workspace/ProfessionalWorkspace.tsx": () => import("../components/mockups/workspace/ProfessionalWorkspace.tsx")
};
