import {
  Monitor,
  Globe,
  ListOrdered,
  ImagePlus,
  FileCode2,
  Puzzle,
  Workflow,
  Rocket,
  Settings,
  TerminalSquare,
  Paintbrush2,
  KeyRound,
  Blocks,
  Plug,
  ScanSearch,
  ShieldCheck,
  BrainCircuit,
  DatabaseZap,
  Cpu,
  Github,
  Wrench,
  BookOpen,
  Activity,
  HeartPulse,
  MessageSquare,
  RotateCcw,
} from "lucide-react";
import type { WorkspaceToolId } from "@workspace/nabuflow-workspace-tools";

export const WORKSPACE_TOOL_ICONS = {
  preview: Monitor,
  "page-map": Globe,
  plan: ListOrdered,
  images: ImagePlus,
  code: FileCode2,
  recipes: Puzzle,
  workflows: Workflow,
  publishing: Rocket,
  manage: Settings,
  terminal: TerminalSquare,
  canvas: Paintbrush2,
  secrets: KeyRound,
  "tools-files": Blocks,
  integrations: Plug,
  checks: ScanSearch,
  security: ShieldCheck,
  knowledge: BrainCircuit,
  database: DatabaseZap,
  runtime: Cpu,
  git: Github,
  logs: Wrench,
  resources: BookOpen,
  analytics: Activity,
  health: HeartPulse,
  comments: MessageSquare,
  "activity-log": Activity,
  checkpoints: RotateCcw,
} satisfies Record<WorkspaceToolId, typeof Monitor>;
