import {
  pgTable,
  serial,
  integer,
  text,
  jsonb,
  boolean,
  timestamp,
  index,
} from "drizzle-orm/pg-core";

/**
 * Ora projects — lightweight folders that group related conversations.
 * A conversation may belong to one project or be standalone (one-off chat).
 * Soft-deleted via `archivedAt`.
 */
export const oraProjectsTable = pgTable(
  "ora_projects",
  {
    id: serial("id").primaryKey(),
    userId: text("user_id").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
  },
  (t) => [index("ora_projects_user_id_idx").on(t.userId)],
);

/**
 * Ora conversations — individual chat threads. Each conversation owns its own
 * message history (stored as a JSONB array, matching the legacy single-transcript
 * shape). `projectId` is null for standalone/one-off chats.
 * Soft-deleted via `archivedAt`.
 */
/**
 * `surface` separates normal Ora chats ("normal") from Help Center support
 * conversations ("support"). Support conversations must NEVER appear in the
 * normal Ora sidebar/history and vice versa — every query is filtered by this
 * column. Existing rows are backfilled to "normal" in the migration.
 */
export const ORA_CONVERSATION_SURFACES = ["normal", "support"] as const;
export type OraConversationSurface = (typeof ORA_CONVERSATION_SURFACES)[number];

/**
 * `titleSource` tracks how the conversation title was set:
 *   "client"  — auto-derived from the first 120 chars of the first message (default)
 *   "ai"      — generated by the async smart-title job after the first assistant reply
 *   "user"    — explicitly renamed by the user (never overwritten by AI)
 */
export const ORA_TITLE_SOURCES = ["client", "ai", "user"] as const;
export type OraTitleSource = (typeof ORA_TITLE_SOURCES)[number];

export const oraConversationsTable = pgTable(
  "ora_conversations",
  {
    id: serial("id").primaryKey(),
    userId: text("user_id").notNull(),
    projectId: integer("project_id"),
    title: text("title"),
    surface: text("surface").notNull().default("normal"),
    messages: jsonb("messages").notNull().default([]),
    // Rolling, model-generated gist of this conversation. Persisted (best-effort,
    // throttled) on message save and read back by Ora's cross-conversation recall
    // so a fact mentioned in one conversation can surface in another. Null until
    // the conversation has enough turns to summarise.
    summary: text("summary"),
    // Number of (non-empty) turns reflected in `summary` — used to throttle
    // re-summarisation (only regenerate once enough new turns accumulate).
    summaryMsgCount: integer("summary_msg_count").notNull().default(0),
    summaryUpdatedAt: timestamp("summary_updated_at", { withTimezone: true }),

    // ── Pin / title source ─────────────────────────────────────────────────
    /** Set when the user pins this conversation; null = not pinned. */
    pinnedAt: timestamp("pinned_at", { withTimezone: true }),
    /** How the current title was produced (see OraTitleSource). */
    titleSource: text("title_source").notNull().default("client"),

    // ── History metadata badges (denormalised for fast list queries) ────────
    /** True if any message in this conversation contains a generated image. */
    metaHasImages: boolean("meta_has_images").notNull().default(false),
    /** True if any message contains a generated file (doc/sheet/slide). */
    metaHasGeneratedFiles: boolean("meta_has_generated_files").notNull().default(false),
    /** True if any message includes web-search citation sources. */
    metaHasSources: boolean("meta_has_sources").notNull().default(false),
    /** True if any message was sent or received via voice (Talk to Ora). */
    metaHasVoice: boolean("meta_has_voice").notNull().default(false),
    /** Short tag for the last significant activity type ('chat'|'image'|'file'|'search'). */
    metaLastActivityType: text("meta_last_activity_type"),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    lastMessageAt: timestamp("last_message_at", { withTimezone: true }).notNull().defaultNow(),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
  },
  (t) => [
    index("ora_conversations_user_id_idx").on(t.userId),
    index("ora_conversations_project_id_idx").on(t.projectId),
    index("ora_conversations_surface_idx").on(t.userId, t.surface),
    index("ora_conversations_pinned_idx").on(t.userId, t.pinnedAt),
  ],
);

/**
 * Per-user Ora settings — lightweight key/value store for preferences that
 * need to survive across devices (e.g. last-active conversation ID for cross-
 * device session restore).
 */
export const oraUserSettingsTable = pgTable("ora_user_settings", {
  userId: text("user_id").primaryKey(),
  settings: jsonb("settings").notNull().default({}),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export type OraProject = typeof oraProjectsTable.$inferSelect;
export type InsertOraProject = typeof oraProjectsTable.$inferInsert;
export type OraConversation = typeof oraConversationsTable.$inferSelect;
export type InsertOraConversation = typeof oraConversationsTable.$inferInsert;
export type OraUserSettings = typeof oraUserSettingsTable.$inferSelect;
